# Imports and helpers

In [36]:
from pathlib import Path
import json
import re
from typing import Any

import pandas as pd
from datasets import load_dataset
from IPython.display import display

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)

NOTEBOOK_DIR = Path.cwd()

# If notebook is in multilingual/notebooks, this gives repo root.
REPO_ROOT = NOTEBOOK_DIR.parents[1]
MULTILINGUAL_DIR = REPO_ROOT / "multilingual"

PROCESSED_ROOT = MULTILINGUAL_DIR / "data" / "processed" / "mera"
PROCESSED_ROOT.mkdir(parents=True, exist_ok=True)

print("NOTEBOOK_DIR:    ", NOTEBOOK_DIR)
print("REPO_ROOT:       ", REPO_ROOT)
print("MULTILINGUAL_DIR:", MULTILINGUAL_DIR)
print("PROCESSED_ROOT:  ", PROCESSED_ROOT)

NOTEBOOK_DIR:     /scratch/workspace/emma/standard-project-m2-mystery-machine/multilingual/notebooks
REPO_ROOT:        /scratch/workspace/emma/standard-project-m2-mystery-machine
MULTILINGUAL_DIR: /scratch/workspace/emma/standard-project-m2-mystery-machine/multilingual
PROCESSED_ROOT:   /scratch/workspace/emma/standard-project-m2-mystery-machine/multilingual/data/processed/mera

In [37]:
HF_DATASET = "MERA-evaluation/MERA"

SELECTED_TASKS = [
    "mamuramu",
    "mathlogicqa",
    "ruopenbookqa",
    "ruworldtree",
    "parus",
]

DROPPED_TASKS = [
    "use", # independent MCQ, many right answers
    "rcb",
    "rwsd",
]

# we do not use test/public_test for now.
ALLOWED_SPLITS = {"train", "validation", "dev"}

LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
CORRUPTION_RE = re.compile(r"[\ufffd\x00-\x08\x0b\x0c\x0e-\x1f]")

In [38]:
def has_corruption(x: Any) -> bool:
    return bool(CORRUPTION_RE.search(str(x)))


def clean_text(x: Any) -> str:
    if x is None:
        return ""
    return str(x).strip()


def to_json_str(x: Any) -> str:
    return json.dumps(x, ensure_ascii=False)


def safe_get(d: Any, key: str, default: Any = "") -> Any:
    if isinstance(d, dict):
        return d.get(key, default)
    return default


def format_abcd(question: str, options: dict[str, Any]) -> str:
    return (
        f"{question}\n\n"
        f"A) {clean_text(options.get('A'))}\n"
        f"B) {clean_text(options.get('B'))}\n"
        f"C) {clean_text(options.get('C'))}\n"
        f"D) {clean_text(options.get('D'))}"
    )


def make_record(
    *,
    subset: str,
    split: str,
    source_id: str,
    task_type: str,
    prompt: str,
    answer: str,
    metadata: dict[str, Any],
) -> dict[str, Any]:
    return {
        "dataset": "mera",
        "subset": subset.lower(),
        "language": "russian",
        "split": split,
        "source_id": source_id,
        "task_type": task_type,
        "prompt": clean_text(prompt),
        "answer": clean_text(answer),
        "metadata": metadata,
    }


def is_valid_record(r: dict[str, Any]) -> bool:
    fields = [r["prompt"], r["answer"]]
    metadata_str = to_json_str(r.get("metadata", {}))

    return (
        r["split"] in {"train", "val"}
        and r["prompt"] != ""
        and r["answer"] != ""
        and not any(has_corruption(x) for x in fields)
        and not has_corruption(metadata_str)
    )

## Task-specific helpers for the subsets

In [39]:
def format_mamuramu(ex: dict[str, Any], split: str, idx: int) -> dict[str, Any]:
    inp = ex["inputs"]
    meta = ex.get("meta", {})

    question = clean_text(inp.get("text"))
    options = {
        "A": inp.get("option_a"),
        "B": inp.get("option_b"),
        "C": inp.get("option_c"),
        "D": inp.get("option_d"),
    }

    return make_record(
        subset="MaMuRAMu",
        split=split,
        source_id=f"MaMuRAMu_{split}_{idx}",
        task_type="mcq",
        prompt=format_abcd(question, options),
        answer=clean_text(ex["outputs"]).upper(),
        metadata={
            "subject": clean_text(inp.get("subject")),
            "domain": clean_text(meta.get("domain")),
            "id": meta.get("id", idx),
        },
    )


def format_mathlogicqa(ex: dict[str, Any], split: str, idx: int) -> dict[str, Any]:
    inp = ex["inputs"]
    meta = ex.get("meta", {})

    question = clean_text(inp.get("text"))
    options = {
        "A": inp.get("option_a"),
        "B": inp.get("option_b"),
        "C": inp.get("option_c"),
        "D": inp.get("option_d"),
    }

    return make_record(
        subset="MathLogicQA",
        split=split,
        source_id=f"MathLogicQA_{split}_{idx}",
        task_type="mcq",
        prompt=format_abcd(question, options),
        answer=clean_text(ex["outputs"]).upper(),
        metadata={
            "task": clean_text(meta.get("task")),
            "id": meta.get("id", idx),
        },
    )


def format_ruopenbookqa(ex: dict[str, Any], split: str, idx: int) -> dict[str, Any]:
    inp = ex["inputs"]
    meta = ex.get("meta", {})

    question = clean_text(inp.get("text") or inp.get("question"))
    options = {
        "A": inp.get("option_a"),
        "B": inp.get("option_b"),
        "C": inp.get("option_c"),
        "D": inp.get("option_d"),
    }

    return make_record(
        subset="ruOpenBookQA",
        split=split,
        source_id=f"ruOpenBookQA_{split}_{idx}",
        task_type="mcq",
        prompt=format_abcd(question, options),
        answer=clean_text(ex["outputs"]).upper(),
        metadata={
            "id": meta.get("id", idx),
        },
    )


def format_ruworldtree(ex: dict[str, Any], split: str, idx: int) -> dict[str, Any]:
    inp = ex["inputs"]
    meta = ex.get("meta", {})

    question = clean_text(inp.get("question") or inp.get("text"))
    options = {
        "A": inp.get("option_a"),
        "B": inp.get("option_b"),
        "C": inp.get("option_c"),
        "D": inp.get("option_d"),
    }

    return make_record(
        subset="ruWorldTree",
        split=split,
        source_id=f"ruWorldTree_{split}_{idx}",
        task_type="mcq",
        prompt=format_abcd(question, options),
        answer=clean_text(ex["outputs"]).upper(),
        metadata={
            "id": meta.get("id", idx),
            "exam_name": clean_text(meta.get("exam_name")),
            "school_grade": meta.get("school_grade", None),
            "knowledge_type": clean_text(meta.get("knowledge_type")),
        },
    )


def format_parus(ex: dict[str, Any], split: str, idx: int) -> dict[str, Any]:
    inp = ex["inputs"]
    meta = ex.get("meta", {})

    q_type = clean_text(meta.get("task"))
    if q_type == "cause":
        q_line = "Что является причиной описанной ситуации?"
    elif q_type == "effect":
        q_line = "Что является следствием описанной ситуации?"
    else:
        q_line = "Какой вариант наиболее правдоподобен?"

    raw_answer = clean_text(ex["outputs"])
    answer_map = {"1": "A", "2": "B"}
    if raw_answer not in answer_map:
        raise ValueError(f"Unexpected PARus answer: {raw_answer!r}")

    prompt = (
        f"{clean_text(inp.get('premise'))}\n\n"
        f"{q_line}\n\n"
        f"A) {clean_text(inp.get('choice1'))}\n"
        f"B) {clean_text(inp.get('choice2'))}"
    )

    return make_record(
        subset="parus",
        split=split,
        source_id=f"parus_{split}_{idx}",
        task_type="mcq",
        prompt=prompt,
        answer=answer_map[raw_answer],
        metadata={
            "task": q_type,
            "id": meta.get("id", idx),
            "raw_answer": raw_answer,
            "option_a": clean_text(inp.get("choice1")),
            "option_b": clean_text(inp.get("choice2")),
        },
    )

def format_rcb(ex: dict[str, Any], split: str, idx: int) -> dict[str, Any]:
    inp = ex["inputs"]
    meta = ex.get("meta", {})

    raw_answer = clean_text(ex["outputs"])
    answer_map = {"1": "A", "2": "B", "3": "C"}
    if raw_answer not in answer_map:
        raise ValueError(f"Unexpected RCB answer: {raw_answer!r}")

    prompt = (
        f"Ситуация:\n{clean_text(inp.get('premise'))}\n\n"
        f"Гипотеза:\n{clean_text(inp.get('hypothesis'))}\n\n"
        "Выберите отношение гипотезы к ситуации:\n"
        "A) гипотеза следует из ситуации\n"
        "B) гипотеза противоречит ситуации\n"
        "C) гипотеза независима от ситуации"
    )

    return make_record(
        subset="rcb",
        split=split,
        source_id=f"rcb_{split}_{idx}",
        task_type="mcq",
        prompt=prompt,
        answer=answer_map[raw_answer],
        metadata={
            "genre": clean_text(meta.get("genre")),
            "verb": clean_text(meta.get("verb")),
            "negation": clean_text(meta.get("negation")),
            "id": meta.get("id", idx),
            "raw_answer": raw_answer,
            "option_a": "гипотеза следует из ситуации",
            "option_b": "гипотеза противоречит ситуации",
            "option_c": "гипотеза независима от ситуации",
        },
    )


# NB: rwsd is binary choice (Yes/No answers), we reformat this to MCQ (2 options), Yes --> A since Y/N pretty balanced, roughly 50/50
def format_rwsd(ex: dict[str, Any], split: str, idx: int) -> dict[str, Any]:
    inp = ex["inputs"]
    meta = ex.get("meta", {})

    raw_answer = clean_text(ex["outputs"]).strip().lower()
    if raw_answer not in {"да", "нет"}:
        raise ValueError(f"Unexpected RWSD answer: {ex['outputs']!r}")

    answer = "A" if raw_answer == "да" else "B"

    prompt = (
        f"Текст:\n{clean_text(inp.get('text'))}\n\n"
        f"Фрагмент 1: {clean_text(inp.get('span1_text'))}\n"
        f"Фрагмент 2: {clean_text(inp.get('span2_text'))}\n\n"
        "Относится ли фрагмент 2 к фрагменту 1?\n\n"
        "A) Да\n"
        "B) Нет"
    )

    return make_record(
        subset="rwsd",
        split=split,
        source_id=f"rwsd_{split}_{idx}",
        task_type="mcq",
        prompt=prompt,
        answer=answer,
        metadata={
            "id": meta.get("id", idx),
            "span1_index": inp.get("span1_index", None),
            "span2_index": inp.get("span2_index", None),
            "raw_answer": clean_text(ex["outputs"]),
            "option_a": "Да",
            "option_b": "Нет",
        },
    )



def format_use(ex: dict[str, Any], split: str, idx: int) -> dict[str, Any]:
    inp = ex["inputs"]
    meta = ex.get("meta", {})

    task = clean_text(inp.get("task"))
    text = clean_text(inp.get("text"))
    choices = clean_text(inp.get("choices"))
    additional_text = clean_text(inp.get("additional_text"))
    use_type = clean_text(meta.get("type"))

    parts = []
    if text:
        parts.append(f"Текст:\n{text}")
    if task:
        parts.append(f"Задание:\n{task}")
    if additional_text:
        parts.append(f"Дополнительный текст:\n{additional_text}")
    if choices:
        parts.append(f"Варианты ответа:\n{choices}")

    prompt = "\n\n".join(parts)
    if use_type.startswith("multiple_choice") or use_type == "matching":
        task_type = "numeric"
    else:
        task_type = "short_answer"

    return make_record(
        subset="use",
        split=split,
        source_id=f"use_{split}_{idx}",
        task_type=task_type,
        prompt=prompt,
        answer=clean_text(ex["outputs"]),
        metadata={
            "id": meta.get("id", idx),
            "id_task": clean_text(meta.get("id_task")),
            "variant": meta.get("variant", None),
            "score": meta.get("score", None),
            "type": use_type,
        },
    )

## Formatter registry

In [40]:
FORMATTERS = {
    "use": format_use,
    "mamuramu": format_mamuramu,
    "mathlogicqa": format_mathlogicqa,
    "ruopenbookqa": format_ruopenbookqa,
    "ruworldtree": format_ruworldtree,
    "parus": format_parus,
    "rcb": format_rcb,
    "rwsd": format_rwsd,
}

In [41]:
for task in SELECTED_TASKS:
    print(f"\n=== {task} ===")
    ds = load_dataset(HF_DATASET, task)
    print(ds)
    for split_name in ds.keys():
        print(f"  {split_name}: {len(ds[split_name])}")

=== mamuramu ===
DatasetDict({
    train: Dataset({
        features: ['instruction', 'inputs', 'outputs', 'meta'],
        num_rows: 285
    })
    test: Dataset({
        features: ['instruction', 'inputs', 'outputs', 'meta'],
        num_rows: 4248
    })
})
  train: 285
  test: 4248

=== mathlogicqa ===
DatasetDict({
    train: Dataset({
        features: ['instruction', 'inputs', 'outputs', 'meta'],
        num_rows: 680
    })
    test: Dataset({
        features: ['instruction', 'inputs', 'outputs', 'meta'],
        num_rows: 1143
    })
})
  train: 680
  test: 1143

=== ruopenbookqa ===
DatasetDict({
    train: Dataset({
        features: ['instruction', 'inputs', 'outputs', 'meta'],
        num_rows: 2338
    })
    test: Dataset({
        features: ['instruction', 'inputs', 'outputs', 'meta'],
        num_rows: 400
    })
})
  train: 2338
  test: 400

=== ruworldtree ===
DatasetDict({
    train: Dataset({
        features: ['instruction', 'inputs', 'outputs', 'meta'],
        num_rows: 115
    })
    test: Dataset({
        features: ['instruction', 'inputs', 'outputs', 'meta'],
        num_rows: 525
    })
})
  train: 115
  test: 525

=== parus ===
DatasetDict({
    train: Dataset({
        features: ['instruction', 'inputs', 'outputs', 'meta'],
        num_rows: 400
    })
    test: Dataset({
        features: ['instruction', 'inputs', 'outputs', 'meta'],
        num_rows: 500
    })
    validation: Dataset({
        features: ['instruction', 'inputs', 'outputs', 'meta'],
        num_rows: 100
    })
})
  train: 400
  test: 500
  validation: 100

# Normalized dataframe

In [42]:
# build normalized mera dataframe
rows = []
rejected_rows = []

for task in SELECTED_TASKS:
    print(f"\nProcessing {task}...")
    ds = load_dataset(HF_DATASET, task)
    formatter = FORMATTERS[task]

    for raw_split in ds.keys():
        if raw_split not in ALLOWED_SPLITS:
            print(f"  skipping split {raw_split}")
            continue

        out_split = "val" if raw_split in {"validation", "dev"} else "train"

        for idx, ex in enumerate(ds[raw_split]):
            try:
                record = formatter(ex, out_split, idx)

                if is_valid_record(record):
                    rows.append(record)
                else:
                    rejected_rows.append({
                        "subset": task,
                        "split": out_split,
                        "source_id": record.get("source_id", f"{task}_{out_split}_{idx}"),
                        "reason": "invalid_record",
                        "raw": to_json_str(ex),
                        "record": to_json_str(record),
                    })

            except Exception as e:
                rejected_rows.append({
                    "subset": task,
                    "split": out_split,
                    "source_id": f"{task}_{out_split}_{idx}",
                    "reason": repr(e),
                    "raw": to_json_str(ex),
                    "record": "",
                })

clean_raw = pd.DataFrame(rows)
rejected = pd.DataFrame(rejected_rows)

print("Raw clean rows:", len(clean_raw))
print("Rejected rows: ", len(rejected))

display(clean_raw.head())

Processing mamuramu...
  skipping split test

Processing mathlogicqa...
  skipping split test

Processing ruopenbookqa...
  skipping split test

Processing ruworldtree...
  skipping split test

Processing parus...
  skipping split test
Raw clean rows: 3918
Rejected rows:  0

,dataset,subset,language,split,source_id,task_type,prompt,answer,metadata
0,mera,mamuramu,russian,train,MaMuRAMu_train_0,mcq,"Какое число больше остальных: 73; 52,5; -5; 75; 32,83?\n\nA) 73\nB) 52,5\nC) -5\nD) 75",D,"{'subject': 'Математика', 'domain': 'elementary_mathematics', 'id': 0}"
1,mera,mamuramu,russian,train,MaMuRAMu_train_1,mcq,"Сколько целых чисел больше 3, но меньше 6?\n\nA) 0\nB) 1\nC) 2\nD) Бесконечно много",C,"{'subject': 'Математика', 'domain': 'elementary_mathematics', 'id': 1}"
2,mera,mamuramu,russian,train,MaMuRAMu_train_2,mcq,Как называется результат при сложении?\n\nA) Делимое\nB) Произведение\nC) Значение суммы\nD) Разность,C,"{'subject': 'Математика', 'domain': 'elementary_mathematics', 'id': 2}"
3,mera,mamuramu,russian,train,MaMuRAMu_train_3,mcq,В часе 60 минут. Чему равна четверть часа?\n\nA) 30 минут\nB) 25 минут\nC) 20 минут\nD) 15 минут,D,"{'subject': 'Математика', 'domain': 'elementary_mathematics', 'id': 3}"
4,mera,mamuramu,russian,train,MaMuRAMu_train_4,mcq,"Как называется часть прямой, ограниченная двумя точками?\n\nA) Луч\nB) Линия\nC) Отрезок\nD) Прямая",C,"{'subject': 'Математика', 'domain': 'elementary_mathematics', 'id': 4}"

In [43]:
# filter to mcq-like and numeric tasks only
KEEP_TASK_TYPES = {"mcq", "numeric", "binary_choice"}

clean = clean_raw[clean_raw["task_type"].isin(KEEP_TASK_TYPES)].copy()
excluded = clean_raw[~clean_raw["task_type"].isin(KEEP_TASK_TYPES)].copy()

print("Raw clean rows:", len(clean_raw))
print("Kept rows:     ", len(clean))
print("Excluded rows: ", len(excluded))

print("\nKept task types:")
display(
    clean.groupby(["subset", "task_type"])
    .size()
    .reset_index(name="n")
    .sort_values(["subset", "task_type"])
)

print("\nExcluded task types:")
if len(excluded):
    display(
        excluded.groupby(["subset", "task_type"])
        .size()
        .reset_index(name="n")
        .sort_values(["subset", "task_type"])
    )
else:
    print("No excluded rows.")

Raw clean rows: 3918
Kept rows:      3918
Excluded rows:  0

Kept task types:

         subset task_type     n
0      mamuramu       mcq   285
1   mathlogicqa       mcq   680
2         parus       mcq   500
3  ruopenbookqa       mcq  2338
4   ruworldtree       mcq   115

Excluded task types:
No excluded rows.

In [44]:
clean.head()

,dataset,subset,language,split,source_id,task_type,prompt,answer,metadata
0,mera,mamuramu,russian,train,MaMuRAMu_train_0,mcq,"Какое число больше остальных: 73; 52,5; -5; 75; 32,83?\n\nA) 73\nB) 52,5\nC) -5\nD) 75",D,"{'subject': 'Математика', 'domain': 'elementary_mathematics', 'id': 0}"
1,mera,mamuramu,russian,train,MaMuRAMu_train_1,mcq,"Сколько целых чисел больше 3, но меньше 6?\n\nA) 0\nB) 1\nC) 2\nD) Бесконечно много",C,"{'subject': 'Математика', 'domain': 'elementary_mathematics', 'id': 1}"
2,mera,mamuramu,russian,train,MaMuRAMu_train_2,mcq,Как называется результат при сложении?\n\nA) Делимое\nB) Произведение\nC) Значение суммы\nD) Разность,C,"{'subject': 'Математика', 'domain': 'elementary_mathematics', 'id': 2}"
3,mera,mamuramu,russian,train,MaMuRAMu_train_3,mcq,В часе 60 минут. Чему равна четверть часа?\n\nA) 30 минут\nB) 25 минут\nC) 20 минут\nD) 15 минут,D,"{'subject': 'Математика', 'domain': 'elementary_mathematics', 'id': 3}"
4,mera,mamuramu,russian,train,MaMuRAMu_train_4,mcq,"Как называется часть прямой, ограниченная двумя точками?\n\nA) Луч\nB) Линия\nC) Отрезок\nD) Прямая",C,"{'subject': 'Математика', 'domain': 'elementary_mathematics', 'id': 4}"

In [45]:
# inspect final counts
print("Counts by subset and split:")
display(
    clean.groupby(["subset", "split"])
    .size()
    .reset_index(name="n")
    .sort_values(["subset", "split"])
)

print("\nTotal by subset:")
display(
    clean.groupby("subset")
    .size()
    .reset_index(name="n")
    .sort_values("n", ascending=False)
)

print("\nRejected rows:")
if len(rejected):
    display(
        rejected.groupby(["subset", "reason"])
        .size()
        .reset_index(name="n")
        .sort_values(["subset", "n"], ascending=[True, False])
    )
else:
    print("No rejected rows.")

Counts by subset and split:

         subset  split     n
0      mamuramu  train   285
1   mathlogicqa  train   680
2         parus  train   400
3         parus    val   100
4  ruopenbookqa  train  2338
5   ruworldtree  train   115

Total by subset:

         subset     n
3  ruopenbookqa  2338
1   mathlogicqa   680
2         parus   500
0      mamuramu   285
4   ruworldtree   115

Rejected rows:
No rejected rows.

In [46]:
# inspect a few final examples
def show_examples(df: pd.DataFrame, subset: str, n: int = 2):
    sub = df[df["subset"].str.lower() == subset.lower()]
    if sub.empty:
        print(f"No rows for {subset}")
        return

    sample = sub.sample(min(n, len(sub)), random_state=42)
    for _, row in sample.iterrows():
        print("=" * 80)
        print(f"subset: {row['subset']} | split: {row['split']} | task_type: {row['task_type']}")
        print("\nPROMPT:")
        print(row["prompt"])
        print("\nANSWER:")
        print(row["answer"])
        print("\nMETADATA:")
        print(row["metadata"])
        print()

for task in SELECTED_TASKS:
    if task in set(clean["subset"]):
        print(f"\n\n### {task}")
        show_examples(clean, task, n=2)

### mamuramu
================================================================================
subset: mamuramu | split: train | task_type: mcq

PROMPT:
Как называется отношение длины окружности к диаметру?

A) Число π
B) Число e
C) Число φ
D) Число γ

ANSWER:
A

METADATA:
{'subject': 'Математика', 'domain': 'high_school_mathematics', 'id': 9}

================================================================================
subset: mamuramu | split: train | task_type: mcq

PROMPT:
Clostridium tetani вызывает следующий тип инфекции

A) бактериемию
B) вирусемию
C) токсинемию
D) септицемию

ANSWER:
C

METADATA:
{'subject': 'Медицина', 'domain': 'virology', 'id': 249}



### mathlogicqa
================================================================================
subset: mathlogicqa | split: train | task_type: mcq

PROMPT:
Если 1 равен d плюс 2. 2, умноженное на d, плюс 2 равно a. То следует вычислить значение a.

A) 0
B) 1
C) -1
D) 4

ANSWER:
A

METADATA:
{'task': 'math', 'id': 647}

================================================================================
subset: mathlogicqa | split: train | task_type: mcq

PROMPT:
Семнадцать рабочих производят на 46 продуктов больше, чем 15 рабочих. Сколько продуктов произведут 20 рабочих?

A) 500
B) 440
C) 450
D) 460

ANSWER:
D

METADATA:
{'task': 'logic', 'id': 607}



### ruopenbookqa
================================================================================
subset: ruopenbookqa | split: train | task_type: mcq

PROMPT:
Если растения собираются распространяться, их семена должны

A) пройти тест
B) быть съеденными
C) отправиться в другое место
D) быть промытыми

ANSWER:
C

METADATA:
{'id': 637}

================================================================================
subset: ruopenbookqa | split: train | task_type: mcq

PROMPT:
Некоторые птицы находят дорогу по

A) геомагнитным линиям
B) дорожным знакам
C) яйцам
D) ориентирам

ANSWER:
A

METADATA:
{'id': 1419}



### ruworldtree
================================================================================
subset: ruworldtree | split: train | task_type: mcq

PROMPT:
Функции корней растения - поддерживать структуру растения и

A) производить пищу
B) принимать воду и питательные вещества
C) производить фрукты
D) помогать прорастанию

ANSWER:
B

METADATA:
{'id': 81, 'exam_name': 'NYSEDREGENTS', 'school_grade': 4, 'knowledge_type': 'DEF'}

================================================================================
subset: ruworldtree | split: train | task_type: mcq

PROMPT:
Шарик падает в стакан с водой. Какая сила притягивает шарик ко дну стакана?

A) гравитация
B) трение
C) электричество
D) магнетизм

ANSWER:
A

METADATA:
{'id': 4, 'exam_name': 'NYSEDREGENTS', 'school_grade': 4, 'knowledge_type': 'CAUSAL'}



### parus
================================================================================
subset: parus | split: train | task_type: mcq

PROMPT:
Мужчина зацепился рукавом за перекладину забора.

Что является следствием описанной ситуации?

A) Он лез через забор.
B) Рукав порвался.

ANSWER:
B

METADATA:
{'task': 'effect', 'id': 361, 'raw_answer': '2', 'option_a': 'Он лез через забор.', 'option_b': 'Рукав порвался.'}

================================================================================
subset: parus | split: train | task_type: mcq

PROMPT:
Его одежда сидит слишком свободно.

Что является причиной описанной ситуации?

A) Он купил её на распродаже.
B) Он сбросил вес.

ANSWER:
B

METADATA:
{'task': 'cause', 'id': 73, 'raw_answer': '2', 'option_a': 'Он купил её на распродаже.', 'option_b': 'Он сбросил вес.'}

In [47]:
# inspect binary-choice label distributions
binary = clean_raw[clean_raw["task_type"] == "binary_choice"].copy()

display(
    binary.groupby(["subset", "answer"])
    .size()
    .reset_index(name="n")
    .sort_values(["subset", "answer"])
)

display(
    binary.groupby(["subset", "split", "answer"])
    .size()
    .reset_index(name="n")
    .sort_values(["subset", "split", "answer"])
)

rwsd = clean_raw[clean_raw["subset"] == "rwsd"].copy()

display(
    rwsd.groupby(["split", "answer"])
    .size()
    .reset_index(name="n")
    .sort_values(["split", "answer"])
)

Empty DataFrame
Columns: [subset, answer, n]
Index: []

Empty DataFrame
Columns: [subset, split, answer, n]
Index: []

Empty DataFrame
Columns: [split, answer, n]
Index: []

In [48]:
# check which hf splits were used
for task in SELECTED_TASKS:
    ds = load_dataset(HF_DATASET, task)
    allowed = [s for s in ds.keys() if s in ALLOWED_SPLITS]
    skipped = [s for s in ds.keys() if s not in ALLOWED_SPLITS]
    print(f"{task:15} allowed={allowed} skipped={skipped}")

mamuramu        allowed=['train'] skipped=['test']
mathlogicqa     allowed=['train'] skipped=['test']
ruopenbookqa    allowed=['train'] skipped=['test']
ruworldtree     allowed=['train'] skipped=['test']
parus           allowed=['train', 'validation'] skipped=['test']

In [52]:
for subset in ["parus", "rcb", "rwsd", "use"]:
    sub = clean[clean["subset"] == subset]
    print(f"\n{subset}")
    display(sub["answer"].value_counts().sort_index())
    display(sub[["prompt", "answer", "metadata"]].sample(min(3, len(sub)), random_state=42))

parus

answer
A    250
B    250
Name: count, dtype: int64

,prompt,answer,metadata
3779,Мужчина зацепился рукавом за перекладину забора.\n\nЧто является следствием описанной ситуации?\n\nA) Он лез через забор.\nB) Рукав порвался.,B,"{'task': 'effect', 'id': 361, 'raw_answer': '2', 'option_a': 'Он лез через забор.', 'option_b': 'Рукав порвался.'}"
3491,Его одежда сидит слишком свободно.\n\nЧто является причиной описанной ситуации?\n\nA) Он купил её на распродаже.\nB) Он сбросил вес.,B,"{'task': 'cause', 'id': 73, 'raw_answer': '2', 'option_a': 'Он купил её на распродаже.', 'option_b': 'Он сбросил вес.'}"
3792,У человека наболело.\n\nЧто является причиной описанной ситуации?\n\nA) Его жена критикует его.\nB) Его мать скончалась.,B,"{'task': 'cause', 'id': 374, 'raw_answer': '2', 'option_a': 'Его жена критикует его.', 'option_b': 'Его мать скончалась.'}"

rcb

Series([], Name: count, dtype: int64)

Empty DataFrame
Columns: [prompt, answer, metadata]
Index: []

rwsd

Series([], Name: count, dtype: int64)

Empty DataFrame
Columns: [prompt, answer, metadata]
Index: []

use

Series([], Name: count, dtype: int64)

Empty DataFrame
Columns: [prompt, answer, metadata]
Index: []

# Save

In [58]:
# save final processed files
clean_to_save = clean.copy()
excluded_to_save = excluded.copy()
rejected_to_save = rejected.copy()

clean_to_save["metadata"] = clean_to_save["metadata"].apply(to_json_str)
if len(excluded_to_save):
    excluded_to_save["metadata"] = excluded_to_save["metadata"].apply(to_json_str)

clean_path = PROCESSED_ROOT / "mera_clean_all.csv"
excluded_path = PROCESSED_ROOT / "mera_excluded_short_answer.csv"
rejected_path = PROCESSED_ROOT / "mera_rejected_all.csv"

clean_to_save.to_csv(clean_path, index=False, encoding="utf-8")
excluded_to_save.to_csv(excluded_path, index=False, encoding="utf-8")
rejected_to_save.to_csv(rejected_path, index=False, encoding="utf-8")


# save jsonl / json versions
jsonl_path = PROCESSED_ROOT / "mera_clean_all.jsonl"
json_path = PROCESSED_ROOT / "mera_clean_all.json"
clean_to_save.to_json(
    jsonl_path,
    orient="records",
    lines=True,
    force_ascii=False,
)
clean_to_save.to_json(
    json_path,
    orient="records",
    indent=2,
    force_ascii=False,
)

print(f"Saved clean JSONL: {jsonl_path}")
print(f"Saved clean JSON:  {json_path}")

print(f"Saved clean:    {clean_path}")
print(f"Saved excluded: {excluded_path}")
print(f"Saved rejected: {rejected_path}")

for subset, sub in clean_to_save.groupby("subset"):
    csv_out_path = PROCESSED_ROOT / f"mera_clean_{subset}.csv"
    jsonl_out_path = PROCESSED_ROOT / f"mera_clean_{subset}.jsonl"
    json_out_path = PROCESSED_ROOT / f"mera_clean_{subset}.json"
    sub.to_csv(csv_out_path, index=False, encoding="utf-8")
    sub.to_json(jsonl_out_path, orient="records", lines=True, force_ascii=False)
    sub.to_json(json_out_path, orient="records", indent=2, force_ascii=False)
    print(f"Saved {subset}: {len(sub)} rows -> {out_path}")

Saved clean JSONL: /scratch/workspace/emma/standard-project-m2-mystery-machine/multilingual/data/processed/mera/mera_clean_all.jsonl
Saved clean JSON:  /scratch/workspace/emma/standard-project-m2-mystery-machine/multilingual/data/processed/mera/mera_clean_all.json
Saved clean:    /scratch/workspace/emma/standard-project-m2-mystery-machine/multilingual/data/processed/mera/mera_clean_all.csv
Saved excluded: /scratch/workspace/emma/standard-project-m2-mystery-machine/multilingual/data/processed/mera/mera_excluded_short_answer.csv
Saved rejected: /scratch/workspace/emma/standard-project-m2-mystery-machine/multilingual/data/processed/mera/mera_rejected_all.csv
Saved mamuramu: 285 rows -> /scratch/workspace/emma/standard-project-m2-mystery-machine/multilingual/data/processed/mera/mera_clean_ruworldtree.csv
Saved mathlogicqa: 680 rows -> /scratch/workspace/emma/standard-project-m2-mystery-machine/multilingual/data/processed/mera/mera_clean_ruworldtree.csv
Saved parus: 500 rows -> /scratch/workspace/emma/standard-project-m2-mystery-machine/multilingual/data/processed/mera/mera_clean_ruworldtree.csv
Saved ruopenbookqa: 2338 rows -> /scratch/workspace/emma/standard-project-m2-mystery-machine/multilingual/data/processed/mera/mera_clean_ruworldtree.csv
Saved ruworldtree: 115 rows -> /scratch/workspace/emma/standard-project-m2-mystery-machine/multilingual/data/processed/mera/mera_clean_ruworldtree.csv

# Final check

In [55]:
df = pd.read_csv(PROCESSED_ROOT / "mera_clean_all.csv")

display(df.groupby(["subset", "split"]).size().reset_index(name="n"))
display(df.groupby(["subset", "task_type"]).size().reset_index(name="n"))
display(df["task_type"].value_counts())
print(df.columns.tolist())
print("has source_id:", "source_id" in df.columns)

         subset  split     n
0      mamuramu  train   285
1   mathlogicqa  train   680
2         parus  train   400
3         parus    val   100
4  ruopenbookqa  train  2338
5   ruworldtree  train   115

         subset task_type     n
0      mamuramu       mcq   285
1   mathlogicqa       mcq   680
2         parus       mcq   500
3  ruopenbookqa       mcq  2338
4   ruworldtree       mcq   115

task_type
mcq    3918
Name: count, dtype: int64

['dataset', 'subset', 'language', 'split', 'source_id', 'task_type', 'prompt', 'answer', 'metadata']
has source_id: True

In [57]:
assert df.columns.tolist() == [
    "dataset",
    "subset",
    "language",
    "split",
    "source_id",
    "task_type",
    "prompt",
    "answer",
    "metadata",
]

assert df["prompt"].notna().all()
assert df["answer"].notna().all()
assert set(df["language"]) == {"russian"}
assert set(df["task_type"]) == {"mcq"}
assert set(df["answer"]).issubset({"A", "B", "C", "D"})
assert not df["prompt"].str.strip().eq("").any()
assert not df["answer"].str.strip().eq("").any()
assert not (df["task_type"] == "short_answer").any()
assert not (df["task_type"] == "numeric").any()
assert set(df["language"]) == {"russian"}
assert df["prompt"].notna().all()
assert df["answer"].notna().all()

In [59]:
# inspect random processed examples from selected subjects only
SAMPLE_N = 10
RANDOM_STATE = 42

SELECTED_SUBJECT_SUBSETS = [
    "mamuramu",
    "mathlogicqa",
    "ruopenbookqa",
    "ruworldtree",
    "parus",
]

sample_lines = []

for subset in SELECTED_SUBJECT_SUBSETS:
    sub = clean_raw[clean_raw["subset"].str.lower() == subset.lower()].copy()

    if sub.empty:
        print(f"No rows for {subset}")
        continue

    sample = sub.sample(n=min(SAMPLE_N, len(sub)), random_state=RANDOM_STATE)

    header = f"\n\n{'=' * 100}\n{subset.upper()} | sampled {len(sample)} / {len(sub)} examples\n{'=' * 100}"
    print(header)
    sample_lines.append(header)

    for i, (_, row) in enumerate(sample.iterrows(), start=1):
        block = (
            f"\n\n--- Example {i} ---\n"
            f"dataset:   {row['dataset']}\n"
            f"subset:    {row['subset']}\n"
            f"language:  {row['language']}\n"
            f"split:     {row['split']}\n"
            f"source_id: {row['source_id']}\n"
            f"task_type: {row['task_type']}\n"
            f"answer:    {row['answer']}\n"
            f"metadata:  {to_json_str(row['metadata'])}\n"
            f"\nPROMPT:\n{row['prompt']}\n"
        )

        print(block)
        sample_lines.append(block)

sample_txt = "\n".join(sample_lines)

sample_path = PROCESSED_ROOT / "mera_v7_random_samples_by_subset.txt"
sample_path.write_text(sample_txt, encoding="utf-8")

print(f"\nSaved random samples to: {sample_path}")

====================================================================================================
MAMURAMU | sampled 10 / 285 examples
====================================================================================================


--- Example 1 ---
dataset:   mera
subset:    mamuramu
language:  russian
split:     train
source_id: MaMuRAMu_train_9
task_type: mcq
answer:    A
metadata:  {"subject": "Математика", "domain": "high_school_mathematics", "id": 9}

PROMPT:
Как называется отношение длины окружности к диаметру?

A) Число π
B) Число e
C) Число φ
D) Число γ



--- Example 2 ---
dataset:   mera
subset:    mamuramu
language:  russian
split:     train
source_id: MaMuRAMu_train_249
task_type: mcq
answer:    C
metadata:  {"subject": "Медицина", "domain": "virology", "id": 249}

PROMPT:
Clostridium tetani вызывает следующий тип инфекции

A) бактериемию
B) вирусемию
C) токсинемию
D) септицемию



--- Example 3 ---
dataset:   mera
subset:    mamuramu
language:  russian
split:     train
source_id: MaMuRAMu_train_157
task_type: mcq
answer:    A
metadata:  {"subject": "Общество", "domain": "professional_psychology", "id": 157}

PROMPT:
Какую деятельность в наибольшей степени можно назвать практикой осознанности?

A) Наблюдение за дыханием
B) Вышивание
C) Приготовление обеда
D) Сочинение стихов



--- Example 4 ---
dataset:   mera
subset:    mamuramu
language:  russian
split:     train
source_id: MaMuRAMu_train_209
task_type: mcq
answer:    C
metadata:  {"subject": "Бизнес", "domain": "business_ethics", "id": 209}

PROMPT:
Что не является стимулом, под влиянием которого бизнес принимает принципы корпоративной социальной ответственности?

A) Этическое потребительство
B) Глобализация и рыночные силы
C) Интересы топ-менеджмента
D) Законодательство и регулирование



--- Example 5 ---
dataset:   mera
subset:    mamuramu
language:  russian
split:     train
source_id: MaMuRAMu_train_75
task_type: mcq
answer:    A
metadata:  {"subject": "Право", "domain": "international_law", "id": 75}

PROMPT:
Какие существуют виды иммунитета государства?

A) Ограниченный, абсолютный
B) Частичный, полный
C) У государства не существует иммунитетов
D) Международный, частно-правовой



--- Example 6 ---
dataset:   mera
subset:    mamuramu
language:  russian
split:     train
source_id: MaMuRAMu_train_232
task_type: mcq
answer:    B
metadata:  {"subject": "Медицина", "domain": "medical_genetics", "id": 232}

PROMPT:
Определите тип наследования болезни. Известно, что она
встречается у особей обоих полов, не в каждом
поколении. Больные дети рождаются у больных и здоровых
родителей.

A) аутосомно-доминантный
B) аутосомно-рецессивный
C) Х-сцепленный доминантный
D) Х-сцепленный рецессивный



--- Example 7 ---
dataset:   mera
subset:    mamuramu
language:  russian
split:     train
source_id: MaMuRAMu_train_264
task_type: mcq
answer:    A
metadata:  {"subject": "Информационные технологии", "domain": "high_school_computer_science", "id": 264}

PROMPT:
Сколько строк напечатает этот код на Си?

#include <stdio.h>

void main()
{
    int k = 0;
    int x = 11;
    for (int i = 0; i < 10; i++)
        for (int j = i; j < 10; j++)
            printf("Строка\n", x);
}

A) 55
B) 100
C) 110
D) 111



--- Example 8 ---
dataset:   mera
subset:    mamuramu
language:  russian
split:     train
source_id: MaMuRAMu_train_170
task_type: mcq
answer:    B
metadata:  {"subject": "Политика", "domain": "high_school_government_and_politics", "id": 170}

PROMPT:
Сколько голосов должен набрать кандидат по мажоритарной системе абсолютного большинства для победы в первом туре выборов?

A) Не менее, чем три четверти голосов
B) Больше половины голосов
C) Больше, чем все другие кандидаты, вместе взятые
D) Больше, чем любой другой кандидат



--- Example 9 ---
dataset:   mera
subset:    mamuramu
language:  russian
split:     train
source_id: MaMuRAMu_train_42
task_type: mcq
answer:    A
metadata:  {"subject": "Физика", "domain": "astronomy", "id": 42}

PROMPT:
Когда Земля находится ближе всего к Солнцу?

A) 1–5 января
B) 1–5 марта
C) 1–5 июня
D) 1–5 сентября



--- Example 10 ---
dataset:   mera
subset:    mamuramu
language:  russian
split:     train
source_id: MaMuRAMu_train_225
task_type: mcq
answer:    C
metadata:  {"subject": "Медицина", "domain": "clinical_knowledge", "id": 225}

PROMPT:
Какое заболевание относится к зоонозным?

A) Столбняк
B) Муковисцидоз
C) Бешенство
D) Болезнь Гиршпрунга



====================================================================================================
MATHLOGICQA | sampled 10 / 680 examples
====================================================================================================


--- Example 1 ---
dataset:   mera
subset:    mathlogicqa
language:  russian
split:     train
source_id: MathLogicQA_train_647
task_type: mcq
answer:    A
metadata:  {"task": "math", "id": 647}

PROMPT:
Если 1 равен d плюс 2. 2, умноженное на d, плюс 2 равно a. То следует вычислить значение a.

A) 0
B) 1
C) -1
D) 4



--- Example 2 ---
dataset:   mera
subset:    mathlogicqa
language:  russian
split:     train
source_id: MathLogicQA_train_607
task_type: mcq
answer:    D
metadata:  {"task": "logic", "id": 607}

PROMPT:
Семнадцать рабочих производят на 46 продуктов больше, чем 15 рабочих. Сколько продуктов произведут 20 рабочих?

A) 500
B) 440
C) 450
D) 460



--- Example 3 ---
dataset:   mera
subset:    mathlogicqa
language:  russian
split:     train
source_id: MathLogicQA_train_63
task_type: mcq
answer:    B
metadata:  {"task": "math", "id": 63}

PROMPT:
Если к 4, умноженному на c, прибавить u, получится -14. -u минус 8 равно 2 умножить на c. Вычислите c.

A) 4
B) -3
C) -2
D) -7



--- Example 4 ---
dataset:   mera
subset:    mathlogicqa
language:  russian
split:     train
source_id: MathLogicQA_train_319
task_type: mcq
answer:    C
metadata:  {"task": "math", "id": 319}

PROMPT:
Если из -m вычесть z, то получится 4. Разность -3, умноженного на m, и 8 равна z. Правда ли, что z равно m?

A) невозможно ответить
B) нет правильного ответа
C) правда
D) неправда



--- Example 5 ---
dataset:   mera
subset:    mathlogicqa
language:  russian
split:     train
source_id: MathLogicQA_train_101
task_type: mcq
answer:    B
metadata:  {"task": "math", "id": 101}

PROMPT:
Произведение x и разности 11 и 6 равно 45. Определите x.

A) 2
B) 9
C) -9
D) 5



--- Example 6 ---
dataset:   mera
subset:    mathlogicqa
language:  russian
split:     train
source_id: MathLogicQA_train_542
task_type: mcq
answer:    C
metadata:  {"task": "logic", "id": 542}

PROMPT:
Билеты в зоопарк стоят 4 доллара для детей, 5 долларов для подростков и 6 долларов для взрослых. В летний сезон в зоопарк ежедневно приходит 1200 человек. В среднем за день, общий доход зоопарка составляет 5300 долларов. На каждые три подростка, посещающих зоопарк, приходится восемь детей. Сколько подростков, детей и взрослых приходили в зоопарк в летний сезон?

A) 250, 710, 240
B) 130, 650, 420
C) 100, 800, 300
D) 200, 600, 400



--- Example 7 ---
dataset:   mera
subset:    mathlogicqa
language:  russian
split:     train
source_id: MathLogicQA_train_260
task_type: mcq
answer:    D
metadata:  {"task": "math", "id": 260}

PROMPT:
Если из 3, умноженных на z, вычесть 5, то получится 4. Найдите/вычислите/определите чему равна переменная z.

A) 5
B) 4
C) -3
D) 3



--- Example 8 ---
dataset:   mera
subset:    mathlogicqa
language:  russian
split:     train
source_id: MathLogicQA_train_165
task_type: mcq
answer:    C
metadata:  {"task": "math", "id": 165}

PROMPT:
3, умноженное на z, минус 8 равно l плюс z. 2, умноженное на z, равно 8. Правда ли, что z больше l?

A) неправда
B) нет правильного ответа
C) правда
D) невозможно ответить



--- Example 9 ---
dataset:   mera
subset:    mathlogicqa
language:  russian
split:     train
source_id: MathLogicQA_train_659
task_type: mcq
answer:    B
metadata:  {"task": "math", "id": 659}

PROMPT:
Известно, что -i равно -1. Произведение 2 и i равно произведению -2 и r. Определите r.

A) 2
B) -1
C) -3
D) 1



--- Example 10 ---
dataset:   mera
subset:    mathlogicqa
language:  russian
split:     train
source_id: MathLogicQA_train_485
task_type: mcq
answer:    B
metadata:  {"task": "math", "id": 485}

PROMPT:
Сумма 7, умноженного на x, и 4, умноженного на x, равняется 55. Вычислите значение x.

A) 5.5
B) 5
C) -5
D) нет правильного ответа



====================================================================================================
RUOPENBOOKQA | sampled 10 / 2338 examples
====================================================================================================


--- Example 1 ---
dataset:   mera
subset:    ruopenbookqa
language:  russian
split:     train
source_id: ruOpenBookQA_train_637
task_type: mcq
answer:    C
metadata:  {"id": 637}

PROMPT:
Если растения собираются распространяться, их семена должны

A) пройти тест
B) быть съеденными
C) отправиться в другое место
D) быть промытыми



--- Example 2 ---
dataset:   mera
subset:    ruopenbookqa
language:  russian
split:     train
source_id: ruOpenBookQA_train_1419
task_type: mcq
answer:    A
metadata:  {"id": 1419}

PROMPT:
Некоторые птицы находят дорогу по

A) геомагнитным линиям
B) дорожным знакам
C) яйцам
D) ориентирам



--- Example 3 ---
dataset:   mera
subset:    ruopenbookqa
language:  russian
split:     train
source_id: ruOpenBookQA_train_387
task_type: mcq
answer:    C
metadata:  {"id": 387}

PROMPT:
Цветов станет больше, если

A) стрекозы будут размножаться чаще
B) опылители будут посещать их редко
C) пчелы будут чаще посещать их
D) им будут доставлять удобрения премиум-класса



--- Example 4 ---
dataset:   mera
subset:    ruopenbookqa
language:  russian
split:     train
source_id: ruOpenBookQA_train_2304
task_type: mcq
answer:    D
metadata:  {"id": 2304}

PROMPT:
Примером предмета домашнего обихода, который способен быть изолятором, может быть

A) бриллиантовая брошь
B) серебряный подсвечник
C) золототая чаша
D) пластиковый половник



--- Example 5 ---
dataset:   mera
subset:    ruopenbookqa
language:  russian
split:     train
source_id: ruOpenBookQA_train_247
task_type: mcq
answer:    C
metadata:  {"id": 247}

PROMPT:
Какой инструмент будет наиболее полезным для помощи комнатным растениям в фотосинтезе

A) музыка
B) тент
C) большое окно
D) удобрение



--- Example 6 ---
dataset:   mera
subset:    ruopenbookqa
language:  russian
split:     train
source_id: ruOpenBookQA_train_1572
task_type: mcq
answer:    C
metadata:  {"id": 1572}

PROMPT:
Вещь может иметь текстуру, легко наблюдаемую и безглазым существом

A) по запаху
B) посредством зрения
C) на ощупь
D) по звуку



--- Example 7 ---
dataset:   mera
subset:    ruopenbookqa
language:  russian
split:     train
source_id: ruOpenBookQA_train_707
task_type: mcq
answer:    B
metadata:  {"id": 707}

PROMPT:
Резина может защитить от

A) холода
B) электричества
C) ожогов
D) огня



--- Example 8 ---
dataset:   mera
subset:    ruopenbookqa
language:  russian
split:     train
source_id: ruOpenBookQA_train_948
task_type: mcq
answer:    D
metadata:  {"id": 948}

PROMPT:
Что будет в результате разведения двух волков?

A) котята
B) страусята
C) лисята
D) волчата



--- Example 9 ---
dataset:   mera
subset:    ruopenbookqa
language:  russian
split:     train
source_id: ruOpenBookQA_train_2104
task_type: mcq
answer:    C
metadata:  {"id": 2104}

PROMPT:
Если объект находится рядом с планетой, а планета вращается вокруг чего-то другого, то объект, вращающийся вокруг планеты, скорее всего,

A) пчелы
B) Солнце
C) Луна
D) уголь



--- Example 10 ---
dataset:   mera
subset:    ruopenbookqa
language:  russian
split:     train
source_id: ruOpenBookQA_train_2094
task_type: mcq
answer:    D
metadata:  {"id": 2094}

PROMPT:
Лягушки зарываются в грязь, чтобы

A) вздремнуть
B) выносить детенышей
C) найти еду
D) сохранить энергию



====================================================================================================
RUWORLDTREE | sampled 10 / 115 examples
====================================================================================================


--- Example 1 ---
dataset:   mera
subset:    ruworldtree
language:  russian
split:     train
source_id: ruWorldTree_train_81
task_type: mcq
answer:    B
metadata:  {"id": 81, "exam_name": "NYSEDREGENTS", "school_grade": 4, "knowledge_type": "DEF"}

PROMPT:
Функции корней растения - поддерживать структуру растения и

A) производить пищу
B) принимать воду и питательные вещества
C) производить фрукты
D) помогать прорастанию



--- Example 2 ---
dataset:   mera
subset:    ruworldtree
language:  russian
split:     train
source_id: ruWorldTree_train_4
task_type: mcq
answer:    A
metadata:  {"id": 4, "exam_name": "NYSEDREGENTS", "school_grade": 4, "knowledge_type": "CAUSAL"}

PROMPT:
Шарик падает в стакан с водой. Какая сила притягивает шарик ко дну стакана?

A) гравитация
B) трение
C) электричество
D) магнетизм



--- Example 3 ---
dataset:   mera
subset:    ruworldtree
language:  russian
split:     train
source_id: ruWorldTree_train_40
task_type: mcq
answer:    C
metadata:  {"id": 40, "exam_name": "NYSEDREGENTS", "school_grade": 4, "knowledge_type": "DEF"}

PROMPT:
Какова основная функция чешуи рыб?

A) помощь в поиске корма
B) привлечение хищников
C) защита рыбы
D) дыхание



--- Example 4 ---
dataset:   mera
subset:    ruworldtree
language:  russian
split:     train
source_id: ruWorldTree_train_69
task_type: mcq
answer:    C
metadata:  {"id": 69, "exam_name": "MEA", "school_grade": 5, "knowledge_type": "DEF,MODEL"}

PROMPT:
Сколько раз Земля вращается вокруг своей оси за один день?

A) 24 раза
B) дважды
C) один раз
D) 365 раз



--- Example 5 ---
dataset:   mera
subset:    ruworldtree
language:  russian
split:     train
source_id: ruWorldTree_train_10
task_type: mcq
answer:    B
metadata:  {"id": 10, "exam_name": "NYSEDREGENTS", "school_grade": 4, "knowledge_type": "MODEL"}

PROMPT:
Какое животное готовится к сезонным изменениям окружающей среды?

A) летучая мышь, летящая ночью
B) белка, хранящая орехи
C) сова, поедающая мышь
D) олень, пьющий воду



--- Example 6 ---
dataset:   mera
subset:    ruworldtree
language:  russian
split:     train
source_id: ruWorldTree_train_45
task_type: mcq
answer:    A
metadata:  {"id": 45, "exam_name": "California Standards Test - Science", "school_grade": 5, "knowledge_type": "DEF,PROP"}

PROMPT:
Студент пытается определить минерал с неметаллическим блеском черного цвета. Его также можно поцарапать ногтем. Согласно справочному листу минералов, неидентифицированный минерал, скорее всего, является

A) слюдой
B) магнетитом
C) роговой обманкой
D) кварцем



--- Example 7 ---
dataset:   mera
subset:    ruworldtree
language:  russian
split:     train
source_id: ruWorldTree_train_70
task_type: mcq
answer:    A
metadata:  {"id": 70, "exam_name": "NYSEDREGENTS", "school_grade": 4, "knowledge_type": "EXAMPLE,CAUSAL"}

PROMPT:
Какой процесс заставляет листья растения увеличиваться в размерах?

A) рост
B) восстановление
C) разложение
D) прорастание



--- Example 8 ---
dataset:   mera
subset:    ruworldtree
language:  russian
split:     train
source_id: ruWorldTree_train_66
task_type: mcq
answer:    C
metadata:  {"id": 66, "exam_name": "MCAS", "school_grade": 5, "knowledge_type": "CAUSAL,MODEL"}

PROMPT:
Тамара купила скейт и комплект для изготовления трамплина. Что из перечисленного наиболее важно для сборки трамплина?

A) изображение, показывающее цвета различных частей трамплина
B) диаграмма, показывающая некоторые способы использования трамплина
C) набор инструкций к набору
D) список цен на другие доступные комплекты



--- Example 9 ---
dataset:   mera
subset:    ruworldtree
language:  russian
split:     train
source_id: ruWorldTree_train_47
task_type: mcq
answer:    D
metadata:  {"id": 47, "exam_name": "MCAS", "school_grade": 5, "knowledge_type": "MODEL"}

PROMPT:
Стальные банки отделяются от алюминиевых в центре переработки. Что из перечисленного является наилучшим способом отделения стальных банок от алюминиевых в центре переработки?

A) отсортировать банки по размеру
B) поместить банки в воду
C) охладить банки до низкой температуры
D) поместить банки под электромагнит



--- Example 10 ---
dataset:   mera
subset:    ruworldtree
language:  russian
split:     train
source_id: ruWorldTree_train_11
task_type: mcq
answer:    B
metadata:  {"id": 11, "exam_name": "ACTAAP", "school_grade": 5, "knowledge_type": "NO TYPE"}

PROMPT:
Илона включает фонарик и подносит предмет к свету. Как она сможет определить непрозрачность объекта?

A) Часть света будет отражаться
B) Свет не будет проникать сквозь него
C) Свет будет преломляться
D) Свет будет четко просвечивать



====================================================================================================
PARUS | sampled 10 / 500 examples
====================================================================================================


--- Example 1 ---
dataset:   mera
subset:    parus
language:  russian
split:     train
source_id: parus_train_361
task_type: mcq
answer:    B
metadata:  {"task": "effect", "id": 361, "raw_answer": "2", "option_a": "Он лез через забор.", "option_b": "Рукав порвался."}

PROMPT:
Мужчина зацепился рукавом за перекладину забора.

Что является следствием описанной ситуации?

A) Он лез через забор.
B) Рукав порвался.



--- Example 2 ---
dataset:   mera
subset:    parus
language:  russian
split:     train
source_id: parus_train_73
task_type: mcq
answer:    B
metadata:  {"task": "cause", "id": 73, "raw_answer": "2", "option_a": "Он купил её на распродаже.", "option_b": "Он сбросил вес."}

PROMPT:
Его одежда сидит слишком свободно.

Что является причиной описанной ситуации?

A) Он купил её на распродаже.
B) Он сбросил вес.



--- Example 3 ---
dataset:   mera
subset:    parus
language:  russian
split:     train
source_id: parus_train_374
task_type: mcq
answer:    B
metadata:  {"task": "cause", "id": 374, "raw_answer": "2", "option_a": "Его жена критикует его.", "option_b": "Его мать скончалась."}

PROMPT:
У человека наболело.

Что является причиной описанной ситуации?

A) Его жена критикует его.
B) Его мать скончалась.



--- Example 4 ---
dataset:   mera
subset:    parus
language:  russian
split:     train
source_id: parus_train_155
task_type: mcq
answer:    B
metadata:  {"task": "cause", "id": 155, "raw_answer": "2", "option_a": "Я пошла наверх.", "option_b": "Я пробежала пять миль."}

PROMPT:
Я выпила кувшин воды.

Что является причиной описанной ситуации?

A) Я пошла наверх.
B) Я пробежала пять миль.



--- Example 5 ---
dataset:   mera
subset:    parus
language:  russian
split:     train
source_id: parus_train_104
task_type: mcq
answer:    A
metadata:  {"task": "cause", "id": 104, "raw_answer": "1", "option_a": "Интервьюер задавал трудные вопросы.", "option_b": "Я была готова к вопросам интервьюера."}

PROMPT:
Я провалила собеседование.

Что является причиной описанной ситуации?

A) Интервьюер задавал трудные вопросы.
B) Я была готова к вопросам интервьюера.



--- Example 6 ---
dataset:   mera
subset:    parus
language:  russian
split:     train
source_id: parus_train_394
task_type: mcq
answer:    B
metadata:  {"task": "cause", "id": 394, "raw_answer": "2", "option_a": "Я выключил свой телефон.", "option_b": "У меня зазвонил телефон."}

PROMPT:
Я вышел с занятия группы.

Что является причиной описанной ситуации?

A) Я выключил свой телефон.
B) У меня зазвонил телефон.



--- Example 7 ---
dataset:   mera
subset:    parus
language:  russian
split:     train
source_id: parus_train_377
task_type: mcq
answer:    B
metadata:  {"task": "cause", "id": 377, "raw_answer": "2", "option_a": "Он перенёс эмоциональную травму.", "option_b": "Он страдал от повреждения головного мозга."}

PROMPT:
Пациент впал в кому.

Что является причиной описанной ситуации?

A) Он перенёс эмоциональную травму.
B) Он страдал от повреждения головного мозга.



--- Example 8 ---
dataset:   mera
subset:    parus
language:  russian
split:     train
source_id: parus_train_124
task_type: mcq
answer:    B