# 1. Imports and inspect

In [49]:
from pathlib import Path
from datasets import load_dataset, get_dataset_config_names, Dataset, DatasetDict
import pandas as pd
import json
import random
import re


pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 300)
pd.set_option("display.width", 200)

SEED = 42
random.seed(SEED)

REPO_ROOT = Path.cwd()
if REPO_ROOT.name == "notebooks":
    REPO_ROOT = REPO_ROOT.parent

OUT_DIR = REPO_ROOT / "data" / "processed"
print("Repo root:", REPO_ROOT)
print("Output root:", OUT_DIR)

Repo root: /scratch/workspace/emma/standard-project-m2-mystery-machine/multilingual
Output root: /scratch/workspace/emma/standard-project-m2-mystery-machine/multilingual/data/processed

In [38]:
# LATAMQA_DATASETS = {
#     "latamqa_es_la": "inria-chile/latamqa_mcq_es-la",
#     "latamqa_es_es": "inria-chile/latamqa_mcq_es-es",
# }
LATAMQA_DATASETS = {
    "latamqa_mcq_blind": "inria-chile/latamqa_mcq_blind",
}

BLEND_DATASET = "nayeon212/BLEnD"
N_EXAMPLES_PER_COUNTRY = 3
SEED = 42

In [37]:
def safe_get_configs(dataset_name):
    try:
        configs = get_dataset_config_names(dataset_name)
        print(f"{dataset_name}: {len(configs)} configs")
        for cfg in configs:
            print(" ", cfg)
        return configs
    except Exception as e:
        print(f"Could not list configs for {dataset_name}: {type(e).__name__}: {e}")
        return None


blend_configs = safe_get_configs(BLEND_DATASET)

nayeon212/BLEnD: 3 configs
  annotations
  short-answer-questions
  multiple-choice-questions

In [10]:
def inspect_datasetdict(ds, name):
    print("=" * 100)
    print(name)
    print(ds)

    for split_name, split_ds in ds.items():
        print("-" * 100)
        print(f"Split: {split_name}")
        print(f"Rows: {len(split_ds)}")
        print("Columns:", split_ds.column_names)

        if len(split_ds) > 0:
            print("First row:")
            print(split_ds[0])


def datasetdict_to_small_df(ds, max_rows_per_split=5):
    rows = []
    for split_name, split_ds in ds.items():
        n = min(max_rows_per_split, len(split_ds))
        for i in range(n):
            row = dict(split_ds[i])
            row["_split"] = split_name
            row["_row_idx"] = i
            rows.append(row)
    return pd.DataFrame(rows)

In [39]:
def get_dataset_from_maybe_datasetdict(obj, split="test"):
    if isinstance(obj, DatasetDict):
        return obj[split]
    if isinstance(obj, Dataset):
        return obj
    raise TypeError(f"Unexpected dataset type: {type(obj)}")

# 2. Inspect

## Blend

In [40]:
BLEND_CONFIG = "multiple-choice-questions"

try:
    blend_raw = load_dataset(BLEND_DATASET, BLEND_CONFIG)
    inspect_datasetdict(blend_raw, f"{BLEND_DATASET} / {BLEND_CONFIG}")
except Exception as e:
    print(f"Failed to load BLEnD with config={BLEND_CONFIG}: {type(e).__name__}: {e}")
    blend_raw = None

====================================================================================================
nayeon212/BLEnD / multiple-choice-questions
DatasetDict({
    test: Dataset({
        features: ['MCQID', 'ID', 'country', 'prompt', 'choices', 'choice_countries', 'answer_idx'],
        num_rows: 305939
    })
})
----------------------------------------------------------------------------------------------------
Split: test
Rows: 305939
Columns: ['MCQID', 'ID', 'country', 'prompt', 'choices', 'choice_countries', 'answer_idx']
First row:
{'MCQID': 'Al-en-01_0', 'ID': 'Al-en-01', 'country': 'UK', 'prompt': 'What is a common snack for preschool kids in the UK? Without any explanation, choose only one from the given alphabet choices(e.g., A, B, C). Provide as JSON format: {"answer_choice":""}\n\nA. candy\nB. cookie\nC. egg\nD. fruit\n\nAnswer:', 'choices': '{\n    "A": "candy",\n    "B": "cookie",\n    "C": "egg",\n    "D": "fruit"\n}', 'choice_countries': '{\n    "A": "North_Korea",\n    "B": "South_Korea",\n    "C": "Mexico",\n    "D": "UK"\n}', 'answer_idx': 'D'}

In [13]:
if blend_raw is not None:
    display(datasetdict_to_small_df(blend_raw, max_rows_per_split=10))

,MCQID,ID,country,prompt,choices,choice_countries,answer_idx,_split,_row_idx
0,Al-en-01_0,Al-en-01,UK,"What is a common snack for preschool kids in the UK? Without any explanation, choose only one from the given alphabet choices(e.g., A, B, C). Provide as JSON format: {""answer_choice"":""""}\n\nA. candy\nB. cookie\nC. egg\nD. fruit\n\nAnswer:","{\n ""A"": ""candy"",\n ""B"": ""cookie"",\n ""C"": ""egg"",\n ""D"": ""fruit""\n}","{\n ""A"": ""North_Korea"",\n ""B"": ""South_Korea"",\n ""C"": ""Mexico"",\n ""D"": ""UK""\n}",D,test,0
1,Al-en-01_1,Al-en-01,UK,"What is a common snack for preschool kids in the UK? Without any explanation, choose only one from the given alphabet choices(e.g., A, B, C). Provide as JSON format: {""answer_choice"":""""}\n\nA. cookie\nB. egg\nC. fruit\nD. jelly\n\nAnswer:","{\n ""A"": ""cookie"",\n ""B"": ""egg"",\n ""C"": ""fruit"",\n ""D"": ""jelly""\n}","{\n ""A"": ""South_Korea"",\n ""B"": ""Mexico"",\n ""C"": ""UK"",\n ""D"": ""West_Java""\n}",C,test,1
2,Al-en-01_2,Al-en-01,UK,"What is a common snack for preschool kids in the UK? Without any explanation, choose only one from the given alphabet choices(e.g., A, B, C). Provide as JSON format: {""answer_choice"":""""}\n\nA. cookie\nB. egg\nC. fruit\nD. jam sandwiches\n\nAnswer:","{\n ""A"": ""cookie"",\n ""B"": ""egg"",\n ""C"": ""fruit"",\n ""D"": ""jam sandwiches""\n}","{\n ""A"": ""South_Korea"",\n ""B"": ""Mexico"",\n ""C"": ""UK"",\n ""D"": ""Algeria""\n}",C,test,2
3,Al-en-01_3,Al-en-01,UK,"What is a common snack for preschool kids in the UK? Without any explanation, choose only one from the given alphabet choices(e.g., A, B, C). Provide as JSON format: {""answer_choice"":""""}\n\nA. chocolate paste\nB. cookie\nC. egg\nD. fruit\n\nAnswer:","{\n ""A"": ""chocolate paste"",\n ""B"": ""cookie"",\n ""C"": ""egg"",\n ""D"": ""fruit""\n}","{\n ""A"": ""Indonesia"",\n ""B"": ""South_Korea"",\n ""C"": ""Mexico"",\n ""D"": ""UK""\n}",D,test,3
4,Al-en-01_4,Al-en-01,UK,"What is a common snack for preschool kids in the UK? Without any explanation, choose only one from the given alphabet choices(e.g., A, B, C). Provide as JSON format: {""answer_choice"":""""}\n\nA. cookie\nB. egg\nC. fruit\nD. semolina\n\nAnswer:","{\n ""A"": ""cookie"",\n ""B"": ""egg"",\n ""C"": ""fruit"",\n ""D"": ""semolina""\n}","{\n ""A"": ""South_Korea"",\n ""B"": ""Mexico"",\n ""C"": ""UK"",\n ""D"": ""Assam""\n}",C,test,4
5,Al-en-01_5,Al-en-01,UK,"What is a common snack for preschool kids in the UK? Without any explanation, choose only one from the given alphabet choices(e.g., A, B, C). Provide as JSON format: {""answer_choice"":""""}\n\nA. cookie\nB. egg\nC. fruit\nD. potato fries\n\nAnswer:","{\n ""A"": ""cookie"",\n ""B"": ""egg"",\n ""C"": ""fruit"",\n ""D"": ""potato fries""\n}","{\n ""A"": ""South_Korea"",\n ""B"": ""Mexico"",\n ""C"": ""UK"",\n ""D"": ""Ethiopia""\n}",C,test,5
6,Al-en-01_6,Al-en-01,UK,"What is a common snack for preschool kids in the UK? Without any explanation, choose only one from the given alphabet choices(e.g., A, B, C). Provide as JSON format: {""answer_choice"":""""}\n\nA. cookie\nB. egg\nC. fruit\nD. noodles\n\nAnswer:","{\n ""A"": ""cookie"",\n ""B"": ""egg"",\n ""C"": ""fruit"",\n ""D"": ""noodles""\n}","{\n ""A"": ""South_Korea"",\n ""B"": ""Mexico"",\n ""C"": ""UK"",\n ""D"": ""Northern_Nigeria""\n}",C,test,6
7,Al-en-01_7,Al-en-01,UK,"What is a common snack for preschool kids in the UK? Without any explanation, choose only one from the given alphabet choices(e.g., A, B, C). Provide as JSON format: {""answer_choice"":""""}\n\nA. candy\nB. cookie\nC. fruit\nD. jelly\n\nAnswer:","{\n ""A"": ""candy"",\n ""B"": ""cookie"",\n ""C"": ""fruit"",\n ""D"": ""jelly""\n}","{\n ""A"": ""North_Korea"",\n ""B"": ""South_Korea"",\n ""C"": ""UK"",\n ""D"": ""West_Java""\n}",C,test,7
8,Al-en-01_8,Al-en-01,UK,"What is a common snack for preschool kids in the UK? Without any explanation, choose only one from the given alphabet choices(e.g., A, B, C). Provide as JSON format: {""answer_choice"":""""}\n\nA. candy\nB. cookie\nC. fruit\nD. jam sandwiches\n\nAnswer:","{\n ""A"": ""candy"",\n ""B"": ""cookie"",\n ""C"": ""fruit"",\n ""D"": ""jam sandwiches""\n}","{\n ""A"": ""North_Korea"",\n ""B"": ""South_Korea"",\n ""C"": ""UK"",\n ""D"": ""Algeria""\n}",C,test,8
9,Al-en-01_9,Al-en-01,UK,"What is a common snack for preschool kids in the UK? Without any explanation, choose only one from the given alphabet choices(e.g., A, B, C). Provide as JSON format: {""answer_choice"":""""}\n\nA. candy\nB. chocolate paste\nC. cookie\nD. fruit\n\nAnswer:","{\n ""A"": ""candy"",\n ""B"": ""chocolate paste"",\n ""C"": ""cookie"",\n ""D"": ""fruit""\n}","{\n ""A"": ""North_Korea"",\n ""B"": ""Indonesia"",\n ""C"": ""South_Korea"",\n ""D"": ""UK""\n}",D,test,9

In [14]:
if blend_raw is not None:
    for split_name, split_ds in blend_raw.items():
        print("=" * 100)
        print(f"BLEnD split: {split_name}")

        df_sample = split_ds.to_pandas()
        print("Columns:", list(df_sample.columns))
        print("Rows:", len(df_sample))

        for col in df_sample.columns:
            col_lower = col.lower()
            if any(key in col_lower for key in ["country", "region", "lang", "locale", "culture"]):
                print(f"\nValue counts for column: {col}")
                print(df_sample[col].value_counts(dropna=False).head(30).to_string())

====================================================================================================
BLEnD split: test
Columns: ['MCQID', 'ID', 'country', 'prompt', 'choices', 'choice_countries', 'answer_idx']
Rows: 305939

Value counts for column: country
country
Ethiopia            22712
South_Korea         21439
Assam               21293
Mexico              20513
China               20410
Greece              20383
Algeria             20364
Azerbaijan          19932
Iran                19371
Spain               19280
Indonesia           18417
North_Korea         17005
UK                  16723
US                  16491
Northern_Nigeria    16317
West_Java           15289

In [19]:
BLEND_COUNTRIES = {
    "Mexico",
    "Spain",
    "China",
    "India",
    "Russia",
}

In [31]:
blend_ds = get_dataset_from_maybe_datasetdict(blend_raw, split="test")
blend_df = blend_ds.to_pandas()

print("BLEnD columns:", list(blend_df.columns))
print("Total BLEnD rows:", len(blend_df))

blend_selected = blend_df[blend_df["country"].isin(BLEND_COUNTRIES)].copy()

print("\nSelected BLEnD rows:", len(blend_selected))
print("\nCounts by country:")
print(blend_selected["country"].value_counts().to_string())

missing_blend = sorted(BLEND_COUNTRIES - set(blend_selected["country"].unique()))
print("\nSelected countries with 0 rows:")
print(missing_blend)

BLEnD columns: ['MCQID', 'ID', 'country', 'prompt', 'choices', 'choice_countries', 'answer_idx']
Total BLEnD rows: 305939

Selected BLEnD rows: 60203

Counts by country:
country
Mexico    20513
China     20410
Spain     19280

Selected countries with 0 rows:
['India', 'Russia']

In [32]:
# BLEnD — examples per selected country

for country in sorted(BLEND_COUNTRIES):
    sub = blend_selected[blend_selected["country"] == country].copy()

    print("=" * 100)
    print(f"BLEnD country: {country}")
    print(f"Rows: {len(sub)}")

    if len(sub) == 0:
        continue

    sample = sub.sample(n=min(N_EXAMPLES_PER_COUNTRY, len(sub)), random_state=SEED)

    for _, row in sample.iterrows():
        print("-" * 100)
        print(f"MCQID: {row.get('MCQID')}")
        print(f"ID: {row.get('ID')}")
        print(f"country: {row.get('country')}")
        print(f"answer_idx: {row.get('answer_idx')}")
        print("prompt:")
        print(row.get("prompt"))
        print("choices:")
        print(row.get("choices"))
        print("choice_countries:")
        print(row.get("choice_countries"))

====================================================================================================
BLEnD country: China
Rows: 20410
----------------------------------------------------------------------------------------------------
MCQID: New-ha-07_817
ID: New-ha-07
country: China
answer_idx: A
prompt:
What food originated from China and can be found all over the world? Without any explanation, choose only one from the given alphabet choices(e.g., A, B, C). Provide as JSON format: {"answer_choice":""}

A. dumplings
B. fish & chips
C. fried rice
D. tacos

Answer:
choices:
{
    "A": "dumplings",
    "B": "fish & chips",
    "C": "fried rice",
    "D": "tacos"
}
choice_countries:
{
    "A": "China",
    "B": "UK",
    "C": "Indonesia",
    "D": "Mexico"
}
----------------------------------------------------------------------------------------------------
MCQID: New-ch-04_128
ID: New-ch-04
country: China
answer_idx: B
prompt:
What kinds of food do people usually eat for late-night snacks in China? Without any explanation, choose only one from the given alphabet choices(e.g., A, B, C). Provide as JSON format: {"answer_choice":""}

A. pizza
B. skewers
C. sweet indonesian pancake
D. tacos

Answer:
choices:
{
    "A": "pizza",
    "B": "skewers",
    "C": "sweet indonesian pancake",
    "D": "tacos"
}
choice_countries:
{
    "A": "US",
    "B": "China",
    "C": "Indonesia",
    "D": "Mexico"
}
----------------------------------------------------------------------------------------------------
MCQID: Na-ko-16_870
ID: Na-ko-16
country: China
answer_idx: D
prompt:
Who is the most famous soccer player in China? Without any explanation, choose only one from the given alphabet choices(e.g., A, B, C). Provide as JSON format: {"answer_choice":""}

A. bambang pamungkas
B. david beckham
C. javier hernandez
D. wu lei

Answer:
choices:
{
    "A": "bambang pamungkas",
    "B": "david beckham",
    "C": "javier hernandez",
    "D": "wu lei"
}
choice_countries:
{
    "A": "Indonesia",
    "B": "UK",
    "C": "Mexico",
    "D": "China"
}
====================================================================================================
BLEnD country: India
Rows: 0
====================================================================================================
BLEnD country: Mexico
Rows: 20513
----------------------------------------------------------------------------------------------------
MCQID: New-in-03_2238
ID: New-in-03
country: Mexico
answer_idx: C
prompt:
What type of food from Mexico is typically served in restaurants overseas? Without any explanation, choose only one from the given alphabet choices(e.g., A, B, C). Provide as JSON format: {"answer_choice":""}

A. paella
B. pyongyang raengmyŏn
C. tacos
D. tea leaf

Answer:
choices:
{
    "A": "paella",
    "B": "pyongyang raengmyŏn",
    "C": "tacos",
    "D": "tea leaf"
}
choice_countries:
{
    "A": "Spain",
    "B": "North_Korea",
    "C": "Mexico",
    "D": "Assam"
}
----------------------------------------------------------------------------------------------------
MCQID: Jo-sp-02_352
ID: Jo-sp-02
country: Mexico
answer_idx: D
prompt:
What is the most popular sport played without a ball in Mexico? Without any explanation, choose only one from the given alphabet choices(e.g., A, B, C). Provide as JSON format: {"answer_choice":""}

A. hockey
B. kabaddi
C. running
D. wrestling

Answer:
choices:
{
    "A": "hockey",
    "B": "kabaddi",
    "C": "running",
    "D": "wrestling"
}
choice_countries:
{
    "A": "US",
    "B": "Assam",
    "C": "Ethiopia",
    "D": "Mexico"
}
----------------------------------------------------------------------------------------------------
MCQID: Na-ko-16_1490
ID: Na-ko-16
country: Mexico
answer_idx: C
prompt:
Who is the most famous soccer player in Mexico? Without any explanation, choose only one from the given alphabet choices(e.g., A, B, C). Provide as JSON format: {"answer_choice":""}

A. bambang pamungkas
B. david beckham
C. javier hernandez
D. zagorakis

Answer:
choices:
{
    "A": "bambang pamungkas",
    "B": "david beckham",
    "C": "javier hernandez",
    "D": "zagorakis"
}
choice_countries:
{
    "A": "Indonesia",
    "B": "UK",
    "C": "Mexico",
    "D": "Greece"
}
====================================================================================================
BLEnD country: Russia
Rows: 0
====================================================================================================
BLEnD country: Spain
Rows: 19280
----------------------------------------------------------------------------------------------------
MCQID: New-gr-05_259
ID: New-gr-05
country: Spain
answer_idx: C
prompt:
What is the most popular grab-and-go breakfast option in Spain? Without any explanation, choose only one from the given alphabet choices(e.g., A, B, C). Provide as JSON format: {"answer_choice":""}

A. cereal
B. chicken porridge
C. coffee
D. soy milk

Answer:
choices:
{
    "A": "cereal",
    "B": "chicken porridge",
    "C": "coffee",
    "D": "soy milk"
}
choice_countries:
{
    "A": "UK",
    "B": "West_Java",
    "C": "Spain",
    "D": "China"
}
----------------------------------------------------------------------------------------------------
MCQID: New-ha-07_1195
ID: New-ha-07
country: Spain
answer_idx: C
prompt:
What food originated from Spain and can be found all over the world? Without any explanation, choose only one from the given alphabet choices(e.g., A, B, C). Provide as JSON format: {"answer_choice":""}

A. couscous
B. kebab
C. spanish omelette
D. traditional mole sauce

Answer:
choices:
{
    "A": "couscous",
    "B": "kebab",
    "C": "spanish omelette",
    "D": "traditional mole sauce"
}
choice_countries:
{
    "A": "Algeria",
    "B": "Iran",
    "C": "Spain",
    "D": "Mexico"
}
----------------------------------------------------------------------------------------------------
MCQID: Ne-ar-31_2399
ID: Ne-ar-31
country: Spain
answer_idx: B
prompt:
What is the most famous dish in Spain? Without any explanation, choose only one from the given alphabet choices(e.g., A, B, C). Provide as JSON format: {"answer_choice":""}

A. fish & chips
B. paella
C. peking roast duck
D. seblak

Answer:
choices:
{
    "A": "fish & chips",
    "B": "paella",
    "C": "peking roast duck",
    "D": "seblak"
}
choice_countries:
{
    "A": "UK",
    "B": "Spain",
    "C": "China",
    "D": "West_Java"
}

# 3. Process

In [78]:
import ast
import json
import random
import re
from collections import Counter
import pandas as pd

BLEND_GROUP_COUNTRIES = {
    "english_spain_mexico": {"Mexico", "Spain"},
    "english_china": {"China"},
}

BLEND_COUNTRIES = set().union(*BLEND_GROUP_COUNTRIES.values())

BLEND_OUT_DIR = OUT_DIR / "blend"
BLEND_OUT_DIR.mkdir(parents=True, exist_ok=True)

N_EXAMPLES = 20

In [71]:
# helpers
PROMPT_INSTRUCTION_RE = re.compile(
    r"\s*Without any explanation, choose only one from the given alphabet choices"
    r"\(e\.g\., A, B, C\)\. Provide as JSON format:\s*\{[\"']answer_choice[\"']:\s*[\"'][\"']\}",
    flags=re.IGNORECASE,
)

TRAILING_ANSWER_RE = re.compile(r"\s*Answer:\s*$", flags=re.IGNORECASE)

INLINE_OPTIONS_RE = re.compile(
    r"\s+A\.\s+.*?\s+B\.\s+.*?\s+C\.\s+.*?\s+D\.\s+.*?(?=\s*Answer:\s*$|$)",
    flags=re.IGNORECASE | re.DOTALL,
)

BAD_ARTIFACT_RE = re.compile(
    r"json|csv|answer_choice|without any explanation|provide as json|answer:\s*$|\bA\.|\bB\.|\bC\.|\bD\.",
    flags=re.IGNORECASE,
)


def parse_choices(x):
    if isinstance(x, dict):
        return {str(k).strip().upper(): str(v).strip() for k, v in x.items()}
    if isinstance(x, str):
        s = x.strip()
        try:
            parsed = json.loads(s)
        except json.JSONDecodeError:
            parsed = ast.literal_eval(s)
        if not isinstance(parsed, dict):
            raise ValueError(f"choices is not a dict: {type(parsed)}")
        return {str(k).strip().upper(): str(v).strip() for k, v in parsed.items()}
    raise ValueError(f"unexpected choices type: {type(x)}")


def clean_blend_prompt(prompt):
    text = str(prompt).strip()
    text = PROMPT_INSTRUCTION_RE.sub("", text)
    text = INLINE_OPTIONS_RE.sub("", text)
    text = TRAILING_ANSWER_RE.sub("", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def normalize_text(x):
    return re.sub(r"\s+", " ", str(x).strip()).lower()

In [79]:
blend_df = blend_raw["test"].to_pandas()
blend_df = blend_df[blend_df["country"].isin(BLEND_COUNTRIES)].copy()
blend_df = blend_df.sample(frac=1, random_state=SEED).reset_index(drop=True)

print("selected rows:", len(blend_df))
print(blend_df["country"].value_counts().to_string())

selected rows: 60203
country
Mexico    20513
China     20410
Spain     19280

In [80]:
rows = []
stats = Counter()

for _, row in blend_df.iterrows():
    try:
        choices = parse_choices(row["choices"])
    except Exception:
        stats["removed_bad_choices_parse"] += 1
        continue

    prompt_clean = clean_blend_prompt(row["prompt"])
    answer = str(row["answer_idx"]).strip().upper()

    if not prompt_clean:
        stats["removed_empty_prompt"] += 1
        continue
    if BAD_ARTIFACT_RE.search(prompt_clean):
        stats["removed_prompt_artifact"] += 1
        continue
    if answer not in choices:
        stats["removed_answer_not_in_choices"] += 1
        continue
    if len(choices) < 2:
        stats["removed_too_few_choices"] += 1
        continue
    if len(set(normalize_text(v) for v in choices.values())) != len(choices):
        stats["removed_duplicate_choice_texts"] += 1
        continue

    out = {
        "MCQID": row.get("MCQID", ""),
        "ID": row.get("ID", ""),
        "country": row.get("country", ""),
        "prompt_clean": prompt_clean,
        "answer_idx": answer,
        "n_choices": len(choices),
    }

    for letter in ["A", "B", "C", "D", "E"]:
        out[f"option_{letter}"] = choices.get(letter, "")

    rows.append(out)

blend_flat = pd.DataFrame(rows)

print("kept after cleaning:", len(blend_flat))
print("removed:")
for key, value in sorted(stats.items()):
    print(f"  {key}: {value}")

display(blend_flat.head())

kept after cleaning: 60203
removed:

,MCQID,ID,country,prompt_clean,answer_idx,n_choices,option_A,option_B,option_C,option_D,option_E
0,Gu-ch-06_199,Gu-ch-06,Mexico,What sports do men like to play the most in Mexico?,D,4,American Football,badminton,cricket,soccer,
1,New-ch-27_349,New-ch-27,China,Who is the most famous boxer in China?,D,4,"""canelo"" alvarez",chris john,hong soo-hwan,zou shiming,
2,Sa-en-16_2248,Sa-en-16,Mexico,What is the most popular soccer team among the people from Mexico?,A,4,america,guangzhou fc,mca,not-applicable,
3,New-en-69_2067,New-en-69,Spain,Which writers are commonly studied in literature class in Spain?,A,4,cervantes,gabriel garcía márquez,haddis alemayehu,william shakespeare,
4,Th-en-24_2491,Th-en-24,Spain,What region in Spain is a major hub for tech workers and start ups?,A,4,barcelona,jakarta,kano,london,

In [81]:
dedup_cols = [
    "prompt_clean",
    "option_A",
    "option_B",
    "option_C",
    "option_D",
    "option_E",
    "answer_idx",
]

before = len(blend_flat)
blend_flat = blend_flat.drop_duplicates(subset=dedup_cols).reset_index(drop=True)

print(f"deduplicated: {before} -> {len(blend_flat)}")
print(blend_flat["country"].value_counts().to_string())

deduplicated: 60203 -> 60203
country
Mexico    20513
China     20410
Spain     19280

In [82]:
def make_blend_prompt(row):
    lines = [str(row["prompt_clean"]).strip(), ""]

    for letter in ["A", "B", "C", "D", "E"]:
        option = str(row.get(f"option_{letter}", "")).strip()
        if option:
            lines.append(f"{letter}) {option}")

    return "\n".join(lines)


def format_blend_example(row, idx, group_name):
    answer = str(row["answer_idx"]).strip().upper()

    return {
        "id": f"blend_{group_name}_{idx}",
        "dataset": "blend",
        "language": "english",
        "task_type": "mcq",
        "prompt": make_blend_prompt(row),
        "answer": answer,
        "metadata": {
            "source_id": str(row.get("MCQID", "")),
            "group_id": str(row.get("ID", "")),
            "country": str(row.get("country", "")),
            "region_group": group_name.replace("english_", ""),
            "source_split": "test",
            "n_choices": int(row.get("n_choices", 0)),
        },
    }


examples_by_group = {}

for group_name, countries in BLEND_GROUP_COUNTRIES.items():
    group_df = blend_flat[blend_flat["country"].isin(countries)].copy().reset_index(drop=True)

    examples = [
        format_blend_example(row, idx, group_name)
        for idx, row in group_df.iterrows()
    ]

    examples_by_group[group_name] = examples
    print(f"{group_name}: {len(examples)} examples")

english_spain_mexico: 39793 examples
english_china: 20410 examples

In [84]:
rng = random.Random(SEED)
for group_name, examples in examples_by_group.items():
    print("=" * 100)
    print(f"group: {group_name}")
    print(f"total examples: {len(examples)}")

    sampled_examples = rng.sample(examples, k=min(N_EXAMPLES, len(examples)))

    for ex in sampled_examples:
        print("-" * 100)
        print(f"id: {ex['id']}")
        print(f"language: {ex['language']}")
        print(f"answer: {ex['answer']}")
        print(f"metadata: {ex['metadata']}")
        print(ex["prompt"])

====================================================================================================
group: english_spain_mexico
total examples: 39793
----------------------------------------------------------------------------------------------------
id: blend_english_spain_mexico_7296
language: english
answer: D
metadata: {'source_id': 'Na-ko-18_179', 'group_id': 'Na-ko-18', 'country': 'Mexico', 'region_group': 'spain_mexico', 'source_split': 'test', 'n_choices': 4}
What is the most common sport girls participate in during physical education classes in Mexico?

A) dance
B) dodgeball
C) jump rope
D) soccer
----------------------------------------------------------------------------------------------------
id: blend_english_spain_mexico_1639
language: english
answer: D
metadata: {'source_id': 'Jod-ch-01_173', 'group_id': 'Jod-ch-01', 'country': 'Mexico', 'region_group': 'spain_mexico', 'source_split': 'test', 'n_choices': 4}
What eating utensils do people commonly used in Mexico?

A) big plate
B) bronze utensils
C) gimchi
D) spoon
----------------------------------------------------------------------------------------------------
id: blend_english_spain_mexico_18024
language: english
answer: B
metadata: {'source_id': 'Ne-ar-26_363', 'group_id': 'Ne-ar-26', 'country': 'Spain', 'region_group': 'spain_mexico', 'source_split': 'test', 'n_choices': 4}
What is the most famous public corporation in Spain?

A) cfe (federal electricity commission)
B) correos
C) microsoft
D) sonatrach
----------------------------------------------------------------------------------------------------
id: blend_english_spain_mexico_16049
language: english
answer: D
metadata: {'source_id': 'New-az-05_406', 'group_id': 'New-az-05', 'country': 'Mexico', 'region_group': 'spain_mexico', 'source_split': 'test', 'n_choices': 4}
What is the most famous region for alcohol production in Mexico?

A) bali
B) gazakh
C) guizhou
D) jalisco
----------------------------------------------------------------------------------------------------
id: blend_english_spain_mexico_14628
language: english
answer: A
metadata: {'source_id': 'Kik-in-10_3862', 'group_id': 'Kik-in-10', 'country': 'Mexico', 'region_group': 'spain_mexico', 'source_split': 'test', 'n_choices': 4}
What is the most popular tourist attraction for foreign visitors in Mexico?

A) beaches
B) borobudur temple
C) gyeongbokgung
D) kasbah
----------------------------------------------------------------------------------------------------
id: blend_english_spain_mexico_9144
language: english
answer: C
metadata: {'source_id': 'Ta-pe-17_454', 'group_id': 'Ta-pe-17', 'country': 'Spain', 'region_group': 'spain_mexico', 'source_split': 'test', 'n_choices': 4}
In the Olympic Games, which sport is the most popular in Spain?

A) diving
B) gymnastics
C) soccer
D) wrestling
----------------------------------------------------------------------------------------------------
id: blend_english_spain_mexico_6717
language: english
answer: C
metadata: {'source_id': 'New-en-90_1025', 'group_id': 'New-en-90', 'country': 'Spain', 'region_group': 'spain_mexico', 'source_split': 'test', 'n_choices': 4}
What is the most famous hotel brand in Spain?

A) camino real
B) home inns
C) nh
D) premier inn
----------------------------------------------------------------------------------------------------
id: blend_english_spain_mexico_35741
language: english
answer: D
metadata: {'source_id': 'New-am-81_118', 'group_id': 'New-am-81', 'country': 'Spain', 'region_group': 'spain_mexico', 'source_split': 'test', 'n_choices': 4}
What is the busiest month for weddings in Spain? (Provide Arabic numerals (e.g., 1) only.)

A) 1
B) 10
C) 4
D) 6
----------------------------------------------------------------------------------------------------
id: blend_english_spain_mexico_5697
language: english
answer: C
metadata: {'source_id': 'New-gr-05_377', 'group_id': 'New-gr-05', 'country': 'Mexico', 'region_group': 'spain_mexico', 'source_split': 'test', 'n_choices': 4}
What is the most popular grab-and-go breakfast option in Mexico?

A) kimbap
B) pasta
C) sandwich
D) soy milk
----------------------------------------------------------------------------------------------------
id: blend_english_spain_mexico_38698
language: english
answer: A
metadata: {'source_id': 'Ca-sp-29_481', 'group_id': 'Ca-sp-29', 'country': 'Spain', 'region_group': 'spain_mexico', 'source_split': 'test', 'n_choices': 4}
What tradition is there in Spain for New Year's Eve?

A) eat the grapes to the rhythm of the clock in the square
B) have dinner toghether
C) not-applicable
D) vasilopita
----------------------------------------------------------------------------------------------------
id: blend_english_spain_mexico_27651
language: english
answer: D
metadata: {'source_id': 'New-ko-06_82', 'group_id': 'New-ko-06', 'country': 'Spain', 'region_group': 'spain_mexico', 'source_split': 'test', 'n_choices': 4}
What is the most popular folk tale in Spain that is typically told to children?

A) Paul Bunyon
B) heungbu and nolbu
C) malin kundang
D) the three little pigs
----------------------------------------------------------------------------------------------------
id: blend_english_spain_mexico_2082
language: english
answer: C
metadata: {'source_id': 'Na-ko-33_197', 'group_id': 'Na-ko-33', 'country': 'Spain', 'region_group': 'spain_mexico', 'source_split': 'test', 'n_choices': 4}
What symbolic food do people from Spain eat on (Lunar) New Year?

A) chakhchoukha
B) dumplings
C) grapes
D) sliced rice cake soup
----------------------------------------------------------------------------------------------------
id: blend_english_spain_mexico_1952
language: english
answer: B
metadata: {'source_id': 'Na-ko-37_765', 'group_id': 'Na-ko-37', 'country': 'Mexico', 'region_group': 'spain_mexico', 'source_split': 'test', 'n_choices': 4}
What is the most popular domestic vacation spot for people from Mexico?

A) bejaia
B) cancun
C) halkidiki
D) mount tangkuban perahu
----------------------------------------------------------------------------------------------------
id: blend_english_spain_mexico_6140
language: english
answer: D
metadata: {'source_id': 'New-gr-06_302', 'group_id': 'New-gr-06', 'country': 'Mexico', 'region_group': 'spain_mexico', 'source_split': 'test', 'n_choices': 4}
What is the most popular food in Mexico among young people?

A) hot pot
B) rice and beans
C) seblak
D) tacos
----------------------------------------------------------------------------------------------------
id: blend_english_spain_mexico_14328
language: english
answer: D
metadata: {'source_id': 'Na-ko-33_363', 'group_id': 'Na-ko-33', 'country': 'Mexico', 'region_group': 'spain_mexico', 'source_split': 'test', 'n_choices': 4}
What symbolic food do people from Mexico eat on (Lunar) New Year?

A) dumplings
B) noodles
C) not-applicable
D) tamales
----------------------------------------------------------------------------------------------------
id: blend_english_spain_mexico_15247
language: english
answer: A
metadata: {'source_id': 'New-in-33_672', 'group_id': 'New-in-33', 'country': 'Spain', 'region_group': 'spain_mexico', 'source_split': 'test', 'n_choices': 4}
What region in Spain is usually associated with mining?

A) asturias
B) benshangul region
C) shanxi
D) sonora
----------------------------------------------------------------------------------------------------
id: blend_english_spain_mexico_33118
language: english
answer: B
metadata: {'source_id': 'Ca-sp-08_247', 'group_id': 'Ca-sp-08', 'country': 'Mexico', 'region_group': 'spain_mexico', 'source_split': 'test', 'n_choices': 4}
What is the most common ingredient used in Mexico's diet?

A) bread
B) corn
C) olive oil
D) wheat
----------------------------------------------------------------------------------------------------
id: blend_english_spain_mexico_39453
language: english
answer: D
metadata: {'source_id': 'New-en-79_2181', 'group_id': 'New-en-79', 'country': 'Mexico', 'region_group': 'spain_mexico', 'source_split': 'test', 'n_choices': 4}
Which region of Mexico is well known for its theatrical performances?

A) athens
B) east coast
C) hyehwa-dong
D) mexico city
----------------------------------------------------------------------------------------------------
id: blend_english_spain_mexico_1739
language: english
answer: D
metadata: {'source_id': 'New-pe-85_1817', 'group_id': 'New-pe-85', 'country': 'Mexico', 'region_group': 'spain_mexico', 'source_split': 'test', 'n_choices': 4}
Where is the most popular tourist destination abroad for people from Mexico?

A) china
B) georgia
C) mexico
D) united states
----------------------------------------------------------------------------------------------------
id: blend_english_spain_mexico_36781
language: english
answer: A
metadata: {'source_id': 'Jo-sp-14_21', 'group_id': 'Jo-sp-14', 'country': 'Mexico', 'region_group': 'spain_mexico', 'source_split': 'test', 'n_choices': 4}
What is the most popular mental sport in Mexico?

A) chess
B) ethiopian dama
C) origami
D) yoga
====================================================================================================
group: english_china
total examples: 20410
----------------------------------------------------------------------------------------------------
id: blend_english_china_6515
language: english
answer: C
metadata: {'source_id': 'Nu-in-40_1304', 'group_id': 'Nu-in-40', 'country': 'China', 'region_group': 'china', 'source_split': 'test', 'n_choices': 4}
Which city is the main destination for job seekers in China?

A) algiers
B) athens
C) beijing
D) guwahati
----------------------------------------------------------------------------------------------------
id: blend_english_china_17856
language: english
answer: D
metadata: {'source_id': 'Jod-ch-13_1712', 'group_id': 'Jod-ch-13', 'country': 'China', 'region_group': 'china', 'source_split': 'test', 'n_choices': 4}
What street food do people from China like to eat?

A) cilok
B) meatball
C) pita gyro
D) roasted sausage
----------------------------------------------------------------------------------------------------
id: blend_english_china_13746
language: english
answer: D
metadata: {'source_id': 'New-ch-38_2262', 'group_id': 'New-ch-38', 'country': 'China', 'region_group': 'china', 'source_split': 'test', 'n_choices': 4}
Which cities or regions are known for their import and export activities in China?

A) barcelona
B) busan
C) new york city
D) shanghai
----------------------------------------------------------------------------------------------------
id: blend_english_china_7223
language: english
answer: D
metadata: {'source_id': 'Al-en-35_63', 'group_id': 'Al-en-35', 'country': 'China', 'region_group': 'china', 'source_split': 'test', 'n_choices': 4}
What do people do to celebrate Christmas in China?

A) decorate their properties
B) family gathering
C) go to church
D) not-applicable
----------------------------------------------------------------------------------------------------
id: blend_english_china_14719
language: english
answer: D
metadata: {'source_id': 'New-ch-38_2391', 'group_id': 'New-ch-38', 'country': 'China', 'region_group': 'china', 'source_split': 'test', 'n_choices': 4}
Which cities or regions are known for their import and export activities in China?

A) barcelona
B) guwahati
C) kano
D) shanghai
----------------------------------------------------------------------------------------------------
id: blend_english_china_19309
language: english
answer: B
metadata: {'source_id': 'New-in-03_1295', 'group_id': 'New-in-03', 'country': 'China', 'region_group': 'china', 'source_split': 'test', 'n_choices': 4}
What type of food from China is typically served in restaurants overseas?

A) dolma
B) fried noodles
C) pork belly
D) tea leaf
----------------------------------------------------------------------------------------------------
id: blend_english_china_9115
language: english
answer: D
metadata: {'source_id': 'New-ch-08_137', 'group_id': 'New-ch-08', 'country': 'China', 'region_group': 'china', 'source_split': 'test', 'n_choices': 4}
What seasoning is indispensable in cooking in China?

A) black pepper
B) cumin
C) olive oil
D) salt
----------------------------------------------------------------------------------------------------
id: blend_english_china_212
language: english
answer: C
metadata: {'source_id': 'New-am-54_1688', 'group_id': 'New-am-54', 'country': 'China', 'region_group': 'china', 'source_split': 'test', 'n_choices': 4}
Which region in China is widely known for its livestock industry?

A) galicia
B) guba
C) inner mongolia
D) sonora
----------------------------------------------------------------------------------------------------
id: blend_english_china_5231
language: english
answer: A
metadata: {'source_id': 'Sa-en-13_588', 'group_id': 'Sa-en-13', 'country': 'China', 'region_group': 'china', 'source_split': 'test', 'n_choices': 4}
What is the food that is most divisive (either love or hate) in China?

A) coriander
B) meat
C) mint chocolate
D) omelette with onion
----------------------------------------------------------------------------------------------------
id: blend_english_china_13848
language: english
answer: B
metadata: {'source_id': 'Ki-pe-24_529', 'group_id': 'Ki-pe-24', 'country': 'China', 'region_group': 'china', 'source_split': 'test', 'n_choices': 4}
What language is taught in schools in China besides English?

A) amharic
B) chinese
C) hausa
D) indonesian language
----------------------------------------------------------------------------------------------------
id: blend_english_china_11149
language: english
answer: D
metadata: {'source_id': 'Na-ko-39_59', 'group_id': 'Na-ko-39', 'country': 'China', 'region_group': 'china', 'source_split': 'test', 'n_choices': 4}
What is typically given as a congratulatory gesture when attending a friend's wedding in China?

A) clothes
B) gift from the wedding list
C) kola nut
D) red envelope
----------------------------------------------------------------------------------------------------
id: blend_english_china_9105
language: english
answer: B
metadata: {'source_id': 'Jo-sp-01_133', 'group_id': 'Jo-sp-01', 'country': 'China', 'region_group': 'china', 'source_split': 'test', 'n_choices': 4}
What is the second most popular sport in China?

A) badminton
B) basketball
C) cricket
D) rugby
----------------------------------------------------------------------------------------------------
id: blend_english_china_5094
language: english
answer: C
metadata: {'source_id': 'New-am-02_485', 'group_id': 'New-am-02', 'country': 'China', 'region_group': 'china', 'source_split': 'test', 'n_choices': 4}
What is the most popular traditional food in China?

A) couscous
B) duck with ash gourd
C) dumplings
D) pastitsio
----------------------------------------------------------------------------------------------------
id: blend_english_china_7055
language: english
answer: C
metadata: {'source_id': 'Al-en-09_324', 'group_id': 'Al-en-09', 'country': 'China', 'region_group': 'china', 'source_split': 'test', 'n_choices': 4}
What is a popular snack at an amusement park in China?

A) churros
B) cotton candy
C) ice cream
D) tea
----------------------------------------------------------------------------------------------------
id: blend_english_china_11029
language: english
answer: C
metadata: {'source_id': 'New-pe-02_646', 'group_id': 'New-pe-02', 'country': 'China', 'region_group': 'china', 'source_split': 'test', 'n_choices': 4}
What is the most famous edible souvenir for tourists in China?

A) fermented cassava
B) not-applicable
C) peking duck
D) sour fish curry
----------------------------------------------------------------------------------------------------
id: blend_english_china_3349
language: english
answer: A
metadata: {'source_id': 'New-en-76_486', 'group_id': 'New-en-76', 'country': 'China', 'region_group': 'china', 'source_split': 'test', 'n_choices': 4}
Which airport in China is the busiest during the holiday season?

A) beijing capital airport
B) heathrow
C) houari boumediene
D) husein sastranegara
----------------------------------------------------------------------------------------------------
id: blend_english_china_3039
language: english
answer: B
metadata: {'source_id': 'Th-en-38_235', 'group_id': 'Th-en-38', 'country': 'China', 'region_group': 'china', 'source_split': 'test', 'n_choices': 4}
What is the most important family holiday in China?

A) christmas
B) lunar new year
C) thanksgiving
D) wedding
----------------------------------------------------------------------------------------------------
id: blend_english_china_12449
language: english
answer: D
metadata: {'source_id': 'Th-en-19_1094', 'group_id': 'Th-en-19', 'country': 'China', 'region_group': 'china', 'source_split': 'test', 'n_choices': 4}
What is a city or region in China known for manufacturing industry?

A) catalonia
B) cikarang
C) kano
D) suzhou
----------------------------------------------------------------------------------------------------
id: blend_english_china_3169
language: english
answer: A
metadata: {'source_id': 'New-en-79_1242', 'group_id': 'New-en-79', 'country': 'China', 'region_group': 'china', 'source_split': 'test', 'n_choices': 4}
Which region of China is well known for its theatrical performances?

A) beijing
B) kano
C) pyongyang
D) tehran
----------------------------------------------------------------------------------------------------
id: blend_english_china_11763
language: english
answer: C
metadata: {'source_id': 'Nu-in-40_1159', 'group_id': 'Nu-in-40', 'country': 'China', 'region_group': 'china', 'source_split': 'test', 'n_choices': 4}
Which city is the main destination for job seekers in China?

A) algiers
B) baku
C) beijing
D) london

In [75]:
rng = random.Random(SEED)
for language, examples in examples_by_language.items():
    print("=" * 100)
    print(f"language: {language}")
    print(f"total examples: {len(examples)}")

    sampled_examples = rng.sample(examples, k=min(N_EXAMPLES, len(examples)))

    for ex in sampled_examples:
        print("-" * 100)
        print(f"id: {ex['id']}")
        print(f"answer: {ex['answer']}")
        print(f"metadata: {ex['metadata']}")
        print(ex["prompt"])

====================================================================================================
language: spanish
total examples: 39793
----------------------------------------------------------------------------------------------------
id: blend_spanish_7296
answer: C
metadata: {'source_id': 'New-ha-07_1452', 'group_id': 'New-ha-07', 'country': 'Spain', 'source_split': 'test', 'n_choices': 4}
What food originated from Spain and can be found all over the world?

A) couscous
B) fried rice
C) paella
D) tea
----------------------------------------------------------------------------------------------------
id: blend_spanish_1639
answer: B
metadata: {'source_id': 'Ta-pe-32_725', 'group_id': 'Ta-pe-32', 'country': 'Spain', 'source_split': 'test', 'n_choices': 4}
What day of the year is usually dedicated to fireworks in Spain?

A) easter
B) end of year
C) mawlid
D) spring festival's eve
----------------------------------------------------------------------------------------------------
id: blend_spanish_18024
answer: D
metadata: {'source_id': 'New-ch-38_5004', 'group_id': 'New-ch-38', 'country': 'Mexico', 'source_split': 'test', 'n_choices': 4}
Which cities or regions are known for their import and export activities in Mexico?

A) kano
B) qeshm
C) sumgait
D) veracruz
----------------------------------------------------------------------------------------------------
id: blend_spanish_16049
answer: D
metadata: {'source_id': 'New-ch-23_116', 'group_id': 'New-ch-23', 'country': 'Mexico', 'source_split': 'test', 'n_choices': 4}
Who is the most famous table tennis player in Mexico?

A) desmond douglas
B) hyun jung-hwa
C) li bun-hui
D) madrid
----------------------------------------------------------------------------------------------------
id: blend_spanish_14628
answer: D
metadata: {'source_id': 'Jo-sp-19_2177', 'group_id': 'Jo-sp-19', 'country': 'Mexico', 'source_split': 'test', 'n_choices': 4}
What region in Mexico has been traditionally associated with agriculture?

A) assam
B) crete
C) henan
D) north of mexico
----------------------------------------------------------------------------------------------------
id: blend_spanish_9144
answer: C
metadata: {'source_id': 'Sa-en-6_428', 'group_id': 'Sa-en-6', 'country': 'Spain', 'source_split': 'test', 'n_choices': 4}
What is the most popular takeaway food in Spain?

A) indian
B) malatang
C) omelette
D) souvlaki
----------------------------------------------------------------------------------------------------
id: blend_spanish_6717
answer: D
metadata: {'source_id': 'New-as-02_86', 'group_id': 'New-as-02', 'country': 'Mexico', 'source_split': 'test', 'n_choices': 4}
What is the most popular wheat-based food item in Mexico?

A) couscous
B) dumpling
C) jeon
D) tortillas
----------------------------------------------------------------------------------------------------
id: blend_spanish_35741
answer: A
metadata: {'source_id': 'Na-ko-15_625', 'group_id': 'Na-ko-15', 'country': 'Mexico', 'source_split': 'test', 'n_choices': 4}
What is the representative nourishing food in Mexico?

A) corn
B) ginseng
C) kebab
D) tempeh
----------------------------------------------------------------------------------------------------
id: blend_spanish_5697
answer: D
metadata: {'source_id': 'New-ha-07_1591', 'group_id': 'New-ha-07', 'country': 'Spain', 'source_split': 'test', 'n_choices': 4}
What food originated from Spain and can be found all over the world?

A) fish & chips
B) fried rice
C) gimchi
D) paella
----------------------------------------------------------------------------------------------------
id: blend_spanish_38698
answer: D
metadata: {'source_id': 'New-ch-83_4682', 'group_id': 'New-ch-83', 'country': 'Mexico', 'source_split': 'test', 'n_choices': 4}
Which city in Mexico hosts festivals the most?

A) addis ababa
B) beijing
C) guwahati
D) mexico city
----------------------------------------------------------------------------------------------------
id: blend_spanish_27651
answer: C
metadata: {'source_id': 'New-am-54_2471', 'group_id': 'New-am-54', 'country': 'Spain', 'source_split': 'test', 'n_choices': 4}
Which region in Spain is widely known for its livestock industry?

A) adamawa
B) afar
C) asturias
D) garut
----------------------------------------------------------------------------------------------------
id: blend_spanish_2082
answer: A
metadata: {'source_id': 'Jod-ch-13_2176', 'group_id': 'Jod-ch-13', 'country': 'Spain', 'source_split': 'test', 'n_choices': 4}
What street food do people from Spain like to eat?

A) churros
B) couscous
C) falafel
D) fish & chips
----------------------------------------------------------------------------------------------------
id: blend_spanish_1952
answer: B
metadata: {'source_id': 'New-en-69_2647', 'group_id': 'New-en-69', 'country': 'Mexico', 'source_split': 'test', 'n_choices': 4}
Which writers are commonly studied in literature class in Mexico?

A) edgar allen poe
B) gabriel garcía márquez
C) jalal al-e ahmad
D) william shakespeare
----------------------------------------------------------------------------------------------------
id: blend_spanish_6140
answer: D
metadata: {'source_id': 'New-am-74_228', 'group_id': 'New-am-74', 'country': 'Mexico', 'source_split': 'test', 'n_choices': 4}
What is the most popular talk show in Mexico?

A) 90 show
B) graham norton
C) rock & roast
D) ventaneando
----------------------------------------------------------------------------------------------------
id: blend_spanish_14328
answer: B
metadata: {'source_id': 'Ji-ko-07_1833', 'group_id': 'Ji-ko-07', 'country': 'Mexico', 'source_split': 'test', 'n_choices': 4}
What is the most famous private company in Mexico?

A) cevital
B) coca-cola
C) samsung
D) zara
----------------------------------------------------------------------------------------------------
id: blend_spanish_15247
answer: D
metadata: {'source_id': 'Nu-in-40_1943', 'group_id': 'Nu-in-40', 'country': 'Spain', 'source_split': 'test', 'n_choices': 4}
Which city is the main destination for job seekers in Spain?

A) abuja
B) athens
C) jakarta
D) madrid
----------------------------------------------------------------------------------------------------
id: blend_spanish_33118
answer: D
metadata: {'source_id': 'Jod-ch-16_166', 'group_id': 'Jod-ch-16', 'country': 'Spain', 'source_split': 'test', 'n_choices': 4}
What is the biggest festival in Spain?

A) bihu
B) glastonbury
C) lunar new year
D) the fallas
----------------------------------------------------------------------------------------------------
id: blend_spanish_39453
answer: C
metadata: {'source_id': 'Ji-ko-03_3914', 'group_id': 'Ji-ko-03', 'country': 'Mexico', 'source_split': 'test', 'n_choices': 4}
Which region/city has the highest number of financial companies in Mexico?

A) guwahati
B) kano
C) mexico city
D) tehran
----------------------------------------------------------------------------------------------------
id: blend_spanish_1739
answer: B
metadata: {'source_id': 'Ca-sp-29_623', 'group_id': 'Ca-sp-29', 'country': 'Mexico', 'source_split': 'test', 'n_choices': 4}
What tradition is there in Mexico for New Year's Eve?

A) eating sabzi polo with fish
B) have dinner toghether
C) not-applicable
D) vasilopita
----------------------------------------------------------------------------------------------------
id: blend_spanish_36781
answer: D
metadata: {'source_id': 'New-en-11_207', 'group_id': 'New-en-11', 'country': 'Mexico', 'source_split': 'test', 'n_choices': 4}
What is the most disliked vegetable in Mexico?

A) brussel sprouts
B) capsicum
C) cauliflower
D) chayote
====================================================================================================
language: chinese
total examples: 0

In [ ]:
for group_name, examples in examples_by_group.items():
    jsonl_path = BLEND_OUT_DIR / f"blend_{group_name}_all.jsonl"
    with jsonl_path.open("w", encoding="utf-8") as f:
        for ex in examples:
            f.write(json.dumps(ex, ensure_ascii=False) + "\n")
    print(f"saved {len(examples)} examples to {jsonl_path}")

saved 39793 examples to /scratch/workspace/emma/standard-project-m2-mystery-machine/multilingual/data/processed/blend/blend_english_spain_mexico_all.jsonl
saved 20410 examples to /scratch/workspace/emma/standard-project-m2-mystery-machine/multilingual/data/processed/blend/blend_english_china_all.jsonl